from app.domain.exceptions.audit_exceptions import (
    AuditLogWriteError,
    UnauthorizedAuditAccessError,
)
from app.domain.exceptions.auth_exceptions import (
    InvalidCredentialsError,
    InvalidOTPError,
    InvalidTokenError,
    TokenExpiredError,
)
from app.domain.exceptions.event_exceptions import (
    EventDateValidationError,
    EventNotFoundError,
    EventStatusTransitionError,
    EventValidationError,
    UnauthorizedEventOperationError,
)
from app.domain.exceptions.event_volunteer_exceptions import (
    EventVolunteerAlreadyExistsError,
    EventVolunteerNotFoundError,
    EventVolunteerValidationError,
    InvalidEventVolunteerStatusTransitionError,
    UnauthorizedEventVolunteerOperationError,
)
from app.domain.exceptions.role_exceptions import (
    DuplicateUserGrantError,
    FeatureNotFoundError,
    RoleAlreadyAssignedError,
    RoleAssignmentNotFoundError,
    RoleNotFoundError,
    UserGrantNotFoundError,
)
from app.domain.exceptions.user_exceptions import (
    AccountDeletionAlreadyScheduledError,
    AccountDeletionGracePeriodExpiredError,
    AliasAlreadyTakenError,
    EmailAlreadyTakenError,
    EmailAlreadyVerifiedError,
    EmailNotVerifiedError,
    OnboardingAlreadyCompletedError,
    SamePasswordError,
    UserInactiveError,
    UserLockedError,
    UserNotFoundError,
)
from app.domain.exceptions.venue_exceptions import (
    UnauthorizedVenueOperationError,
    VenueAlreadyExistsError,
    VenueInvalidTypeError,
    VenueNotFoundError,
    VenueValidationError,
)
from app.domain.exceptions.venue_rating_exceptions import (
    UnauthorizedRatingOperationError,
    VenueRatingAlreadyExistsError,
    VenueRatingNotFoundError,
    VenueRatingValidationError,
)
from app.domain.exceptions.volunteer_application_exceptions import (
    ApplicationStatusError,
    UnauthorizedApplicationOperationError,
    VolunteerApplicationAlreadyExistsError,
    VolunteerApplicationNotFoundError,
    VolunteerApplicationValidationError,
)
from app.domain.exceptions.volunteer_exceptions import (
    UnauthorizedVolunteerOperationError,
    VolunteerAlreadyExistsError,
    VolunteerInactiveError,
    VolunteerNotFoundError,
    VolunteerValidationError,
)

__all__ = [
    "EmailAlreadyTakenError",
    "EmailAlreadyVerifiedError",
    "UserNotFoundError",
    "UserLockedError",
    "UserInactiveError",
    "EmailNotVerifiedError",
    "OnboardingAlreadyCompletedError",
    "SamePasswordError",
    "AliasAlreadyTakenError",
    "AccountDeletionAlreadyScheduledError",
    "AccountDeletionGracePeriodExpiredError",
    "InvalidTokenError",
    "TokenExpiredError",
    "InvalidCredentialsError",
    "InvalidOTPError",
    "AuditLogWriteError",
    "UnauthorizedAuditAccessError",
    "RoleNotFoundError",
    "RoleAssignmentNotFoundError",
    "RoleAlreadyAssignedError",
    "FeatureNotFoundError",
    "UserGrantNotFoundError",
    "DuplicateUserGrantError",
    "VenueNotFoundError",
    "UnauthorizedVenueOperationError",
    "VenueValidationError",
    "VenueAlreadyExistsError",
    "VenueInvalidTypeError",
    "VenueRatingNotFoundError",
    "UnauthorizedRatingOperationError",
    "VenueRatingValidationError",
    "VenueRatingAlreadyExistsError",
    "VolunteerNotFoundError",
    "VolunteerValidationError",
    "VolunteerAlreadyExistsError",
    "UnauthorizedVolunteerOperationError",
    "VolunteerInactiveError",
    "VolunteerApplicationNotFoundError",
    "VolunteerApplicationValidationError",
    "VolunteerApplicationAlreadyExistsError",
    "UnauthorizedApplicationOperationError",
    "ApplicationStatusError",
    "EventNotFoundError",
    "EventValidationError",
    "UnauthorizedEventOperationError",
    "EventStatusTransitionError",
    "EventDateValidationError",
    "EventVolunteerNotFoundError",
    "EventVolunteerValidationError",
    "EventVolunteerAlreadyExistsError",
    "UnauthorizedEventVolunteerOperationError",
    "InvalidEventVolunteerStatusTransitionError",
]
