// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ActionType
 */
export const zActionType = z.enum([
    'create',
    'read',
    'update',
    'delete',
    'login',
    'logout',
    'verify',
    'export',
    'import'
]);

/**
 * AddVolunteerRequest
 */
export const zAddVolunteerRequest = z.object({
    target_user_id: z.uuid(),
    contact_phone: z.string().min(7).max(20),
    volunteer_role_id: z.uuid()
});

/**
 * AdminDeleteAccountRequest
 */
export const zAdminDeleteAccountRequest = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * AdminUserAccountPaginationResponse
 */
export const zAdminUserAccountPaginationResponse = z.object({
    page: z.int(),
    page_size: z.int(),
    total_count: z.int(),
    total_pages: z.int(),
    has_next: z.boolean(),
    has_previous: z.boolean()
});

/**
 * AgeGroup
 */
export const zAgeGroup = z.enum([
    'child',
    'teen',
    'adult',
    'senior'
]);

/**
 * AppFeedbackRecordResponse
 */
export const zAppFeedbackRecordResponse = z.object({
    id: z.uuid(),
    rating: z.int(),
    comment: z.string().nullable(),
    created_at: z.iso.datetime()
});

/**
 * AppFeedbackListData
 */
export const zAppFeedbackListData = z.object({
    feedback: z.array(zAppFeedbackRecordResponse),
    total: z.int(),
    page: z.int(),
    page_size: z.int(),
    total_pages: z.int()
});

/**
 * AppFeedbackListResponse
 */
export const zAppFeedbackListResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Feedback retrieved successfully'),
    data: zAppFeedbackListData
});

/**
 * ApplicationStatus
 */
export const zApplicationStatus = z.enum([
    'pending',
    'approved',
    'rejected',
    'withdrawn'
]);

/**
 * ApplyEventVolunteerRequest
 */
export const zApplyEventVolunteerRequest = z.object({
    message: z.string().max(500).nullish()
});

/**
 * AssignRoleRequest
 */
export const zAssignRoleRequest = z.object({
    user_id: z.uuid(),
    role_id: z.uuid(),
    expires_at: z.iso.datetime().nullish()
});

/**
 * AssignVolunteerRequest
 */
export const zAssignVolunteerRequest = z.object({
    alias: z.string()
});

/**
 * AttendedEventResponse
 */
export const zAttendedEventResponse = z.object({
    participant_id: z.uuid(),
    event_id: z.uuid(),
    event_title: z.string(),
    event_start_date: z.iso.datetime(),
    event_end_date: z.iso.datetime(),
    event_banner_url: z.string().nullish(),
    session_id: z.uuid(),
    session_title: z.string(),
    session_start_datetime: z.iso.datetime(),
    session_end_datetime: z.iso.datetime(),
    attended_at: z.iso.datetime().nullish()
});

/**
 * AuditLogStatus
 */
export const zAuditLogStatus = z.enum(['success', 'failure']);

/**
 * AuditLogResponse
 */
export const zAuditLogResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid().nullable(),
    ip_address: z.string().nullable(),
    user_agent: z.string().nullable(),
    timestamp: z.iso.datetime(),
    action_type: zActionType,
    resource_type: z.string(),
    resource_id: z.string().nullable(),
    status: zAuditLogStatus,
    old_values: z.record(z.string(), z.unknown()).nullable(),
    new_values: z.record(z.string(), z.unknown()).nullable(),
    additional_context: z.record(z.string(), z.unknown()).nullable()
});

/**
 * ChangePasswordRequest
 */
export const zChangePasswordRequest = z.object({
    current_password: z.string().min(1),
    new_password: z.string().min(8)
});

/**
 * ChangePasswordResponse
 */
export const zChangePasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password changed successfully. All active sessions have been invalidated.')
});

/**
 * ChangeUserEmailRequest
 */
export const zChangeUserEmailRequest = z.object({
    email: z.email()
});

/**
 * ChangeUserEmailResponse
 */
export const zChangeUserEmailResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    email: z.email(),
    message: z.string().optional().default('User email updated successfully. A new verification link has been sent.')
});

/**
 * ChangeUserRoleRequest
 */
export const zChangeUserRoleRequest = z.object({
    role_id: z.uuid()
});

/**
 * CheckAliasResponse
 */
export const zCheckAliasResponse = z.object({
    success: z.boolean().optional().default(true),
    alias: z.string(),
    available: z.boolean()
});

/**
 * CheckInParticipantQrCodeRequest
 */
export const zCheckInParticipantQrCodeRequest = z.object({
    token: z.string()
});

/**
 * CreateEventFeedbackRequest
 */
export const zCreateEventFeedbackRequest = z.object({
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(2000).nullish(),
    suggestion: z.string().max(2000).nullish()
});

/**
 * CreateVolunteerRoleRequest
 */
export const zCreateVolunteerRoleRequest = z.object({
    name: z.string().min(2).max(100),
    description: z.string().max(500).nullish()
});

/**
 * DeadJobResponse
 */
export const zDeadJobResponse = z.object({
    job_id: z.string(),
    function: z.string(),
    args: z.array(z.unknown()),
    kwargs: z.record(z.string(), z.unknown()),
    job_try: z.int(),
    enqueue_time: z.iso.datetime(),
    finish_time: z.iso.datetime().nullable(),
    error: z.string()
});

/**
 * DeleteAccountRequest
 */
export const zDeleteAccountRequest = z.object({
    current_password: z.string().min(1),
    reason: z.string().min(1).max(500).nullish()
});

/**
 * DeleteAccountResponse
 */
export const zDeleteAccountResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    deletion_requested_at: z.iso.datetime(),
    deletion_scheduled_for: z.iso.datetime(),
    requested_by: z.uuid(),
    grace_period_days: z.int().optional().default(30),
    message: z.string().optional().default('Account deletion scheduled. The account will be permanently deleted after the 30-day grace period unless the user logs in before then.')
});

/**
 * DeleteJobResponse
 */
export const zDeleteJobResponse = z.object({
    success: z.boolean().optional().default(true),
    job_id: z.string(),
    deleted: z.boolean()
});

/**
 * EducationLevel
 */
export const zEducationLevel = z.enum([
    'no_formal_education',
    'elementary_level',
    'elementary_graduate',
    'junior_high_school_level',
    'junior_high_school_graduate',
    'senior_high_school_level',
    'senior_high_school_graduate',
    'vocational_trade_certificate',
    'college_level_undergraduate',
    'associate_degree',
    'bachelors_degree',
    'masters_degree',
    'doctorate_degree'
]);

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    success: z.boolean().optional().default(false),
    message: z.string()
});

/**
 * EventBannerUploadData
 */
export const zEventBannerUploadData = z.object({
    upload_url: z.string(),
    object_key: z.string(),
    public_url: z.string(),
    expires_in: z.int()
});

/**
 * EventBannerUploadRequest
 */
export const zEventBannerUploadRequest = z.object({
    content_type: z.string().min(1).max(100)
});

/**
 * EventFeedbackPaginationMeta
 */
export const zEventFeedbackPaginationMeta = z.object({
    total: z.int(),
    limit: z.int(),
    offset: z.int()
});

/**
 * EventFeedbackRecordResponse
 */
export const zEventFeedbackRecordResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    event_id: z.uuid(),
    participant_id: z.uuid(),
    rating: z.int(),
    comment: z.string().nullable(),
    suggestion: z.string().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * EventFeedbackListResponse
 */
export const zEventFeedbackListResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event feedback retrieved successfully.'),
    data: z.array(zEventFeedbackRecordResponse),
    meta: zEventFeedbackPaginationMeta
});

/**
 * EventFeedbackResponse
 */
export const zEventFeedbackResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event feedback submitted successfully.'),
    data: zEventFeedbackRecordResponse
});

/**
 * EventParticipantRecord
 */
export const zEventParticipantRecord = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    event_session_id: z.uuid(),
    status: z.string(),
    is_checked_in: z.boolean(),
    checked_in_time: z.iso.datetime().nullable(),
    checked_in_by: z.uuid().nullable(),
    user_first_name: z.string().nullish(),
    user_last_name: z.string().nullish(),
    user_alias: z.string().nullish(),
    user_profile_picture_url: z.string().nullish(),
    event_session_title: z.string().nullish(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * EventParticipantRecordResponse
 */
export const zEventParticipantRecordResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    event_session_id: z.uuid(),
    status: z.string(),
    is_checked_in: z.boolean(),
    checked_in_time: z.iso.datetime().nullable(),
    checked_in_by: z.uuid().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * CheckInParticipantResponse
 */
export const zCheckInParticipantResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Participant checked in successfully.'),
    data: zEventParticipantRecordResponse
});

/**
 * EventParticipantStatus
 */
export const zEventParticipantStatus = z.enum([
    'registered',
    'attended',
    'cancelled',
    'no_show'
]);

/**
 * EventRecordResponse
 */
export const zEventRecordResponse = z.object({
    id: z.uuid(),
    title: z.string(),
    description: z.string(),
    start_date: z.iso.datetime(),
    end_date: z.iso.datetime(),
    status: z.string(),
    created_by: z.uuid(),
    banner_url: z.string().nullish(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * EventBannerUploadResponse
 */
export const zEventBannerUploadResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Banner upload URL generated. Use upload_url to PUT your image directly to storage.'),
    data: zEventRecordResponse,
    upload: zEventBannerUploadData
});

/**
 * EventDeletedResponse
 */
export const zEventDeletedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event deleted successfully.'),
    data: zEventRecordResponse
});

/**
 * EventListResponse
 */
export const zEventListResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Events retrieved successfully.'),
    data: z.array(zEventRecordResponse),
    total: z.int(),
    page: z.int(),
    page_size: z.int(),
    total_pages: z.int()
});

/**
 * EventMetadataUpdatedResponse
 */
export const zEventMetadataUpdatedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event updated successfully.'),
    data: zEventRecordResponse
});

/**
 * EventSessionCreateRequest
 */
export const zEventSessionCreateRequest = z.object({
    venue_id: z.uuid(),
    title: z.string().min(5).max(255),
    description: z.string().max(5000).nullish(),
    start_datetime: z.iso.datetime(),
    end_datetime: z.iso.datetime(),
    max_slots: z.int().gt(0).nullish()
});

/**
 * EventCreateRequest
 */
export const zEventCreateRequest = z.object({
    title: z.string().min(1).max(255),
    description: z.string().min(1),
    start_date: z.iso.datetime(),
    end_date: z.iso.datetime(),
    banner_url: z.string().max(512).nullish(),
    sessions: z.array(zEventSessionCreateRequest).min(1)
});

/**
 * EventSessionRecordResponse
 */
export const zEventSessionRecordResponse = z.object({
    id: z.uuid(),
    event_id: z.uuid(),
    venue_id: z.uuid(),
    venue_name: z.string().nullish(),
    venue_location: z.string().nullish(),
    title: z.string(),
    description: z.string().nullable(),
    start_datetime: z.iso.datetime(),
    end_datetime: z.iso.datetime(),
    status: z.string(),
    max_slots: z.int().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * EventDetailResponse
 */
export const zEventDetailResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event retrieved successfully.'),
    data: zEventRecordResponse,
    sessions: z.array(zEventSessionRecordResponse)
});

/**
 * EventSessionCreatedResponse
 */
export const zEventSessionCreatedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event session created successfully.'),
    data: zEventSessionRecordResponse
});

/**
 * EventSessionDeletedResponse
 */
export const zEventSessionDeletedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event session deleted successfully.'),
    data: zEventSessionRecordResponse
});

/**
 * EventSessionStatus
 */
export const zEventSessionStatus = z.enum([
    'draft',
    'posted',
    'started',
    'cancelled',
    'ended',
    'postponed'
]);

/**
 * EventSessionStatusUpdateRequest
 */
export const zEventSessionStatusUpdateRequest = z.object({
    new_status: zEventSessionStatus
});

/**
 * EventSessionStatusUpdatedResponse
 */
export const zEventSessionStatusUpdatedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event session status updated successfully.'),
    data: zEventSessionRecordResponse
});

/**
 * EventSessionUpdateRequest
 */
export const zEventSessionUpdateRequest = z.object({
    venue_id: z.uuid(),
    title: z.string().min(5).max(255),
    description: z.string().max(5000).nullish(),
    start_datetime: z.iso.datetime(),
    end_datetime: z.iso.datetime(),
    max_slots: z.int().gt(0).nullish()
});

/**
 * EventSessionUpdatedResponse
 */
export const zEventSessionUpdatedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event session updated successfully.'),
    data: zEventSessionRecordResponse
});

/**
 * EventStatus
 */
export const zEventStatus = z.enum([
    'draft',
    'posted',
    'started',
    'cancelled',
    'ended',
    'postponed'
]);

/**
 * EventStatusUpdateRequest
 */
export const zEventStatusUpdateRequest = z.object({
    new_status: zEventStatus
});

/**
 * EventStatusUpdatedResponse
 */
export const zEventStatusUpdatedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event status updated successfully.'),
    data: zEventRecordResponse
});

/**
 * EventSummaryResponse
 */
export const zEventSummaryResponse = z.object({
    id: z.uuid(),
    title: z.string(),
    status: z.string(),
    start_date: z.iso.datetime(),
    end_date: z.iso.datetime(),
    created_at: z.iso.datetime().nullish()
});

/**
 * EventUpdateRequest
 */
export const zEventUpdateRequest = z.object({
    title: z.string().min(1).max(255),
    description: z.string().min(1),
    start_date: z.iso.datetime(),
    end_date: z.iso.datetime(),
    banner_url: z.string().max(512).nullish()
});

/**
 * EventVolunteerRecordResponse
 */
export const zEventVolunteerRecordResponse = z.object({
    id: z.uuid(),
    volunteer_id: z.uuid(),
    event_id: z.uuid(),
    status: z.string(),
    volunteer_user_id: z.uuid().nullish(),
    volunteer_first_name: z.string().nullish(),
    volunteer_last_name: z.string().nullish(),
    volunteer_alias: z.string().nullish(),
    volunteer_profile_picture_url: z.string().nullish(),
    volunteer_role_name: z.string().nullish(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * EventVolunteerListResponse
 */
export const zEventVolunteerListResponse = z.object({
    success: z.boolean(),
    message: z.string(),
    data: z.array(zEventVolunteerRecordResponse)
});

/**
 * EventVolunteerResponse
 */
export const zEventVolunteerResponse = z.object({
    success: z.boolean(),
    message: z.string(),
    data: zEventVolunteerRecordResponse
});

/**
 * EventVolunteerStatus
 */
export const zEventVolunteerStatus = z.enum([
    'pending',
    'joined',
    'left',
    'rejected'
]);

/**
 * EventWithSessionsResponse
 */
export const zEventWithSessionsResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Event created successfully.'),
    data: zEventRecordResponse,
    sessions: z.array(zEventSessionRecordResponse)
});

/**
 * EventsAttendedResponse
 */
export const zEventsAttendedResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Events attended retrieved successfully.'),
    data: z.array(zAttendedEventResponse)
});

/**
 * FeatureCreateRequest
 */
export const zFeatureCreateRequest = z.object({
    slug: z.string().min(1).max(100),
    name: z.string().min(1).max(150),
    description: z.string().max(1000).nullish(),
    is_enabled: z.boolean().optional().default(true)
});

/**
 * FeatureRecordResponse
 */
export const zFeatureRecordResponse = z.object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    is_enabled: z.boolean()
});

/**
 * FeatureListResponse
 */
export const zFeatureListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zFeatureRecordResponse)
});

/**
 * FeatureResponse
 */
export const zFeatureResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zFeatureRecordResponse,
    message: z.string().optional().default('Feature saved successfully.')
});

/**
 * FeatureUpdateRequest
 */
export const zFeatureUpdateRequest = z.object({
    slug: z.string().min(1).max(100),
    name: z.string().min(1).max(150),
    description: z.string().max(1000).nullish(),
    is_enabled: z.boolean().optional().default(true)
});

/**
 * ForgotPasswordRequest
 */
export const zForgotPasswordRequest = z.object({
    email: z.email()
});

/**
 * ForgotPasswordResponse
 */
export const zForgotPasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('If that email address is in our system, you will receive a password reset link shortly.')
});

/**
 * Gender
 */
export const zGender = z.enum(['male', 'female']);

/**
 * GrantEffect
 */
export const zGrantEffect = z.enum(['allow', 'deny']);

/**
 * GrantFeatureResponse
 */
export const zGrantFeatureResponse = z.object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    is_enabled: z.boolean()
});

/**
 * GrantFeatureListResponse
 */
export const zGrantFeatureListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zGrantFeatureResponse)
});

/**
 * ListDeadJobsResponse
 */
export const zListDeadJobsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zDeadJobResponse),
    total: z.int(),
    page: z.int(),
    limit: z.int(),
    total_pages: z.int()
});

/**
 * LoginHistoryEntryResponse
 */
export const zLoginHistoryEntryResponse = z.object({
    id: z.uuid(),
    ip_address: z.string().nullish(),
    user_agent: z.string().nullish(),
    browser: z.string().nullish(),
    os: z.string().nullish(),
    device_type: z.string().nullish(),
    city: z.string().nullish(),
    region: z.string().nullish(),
    country: z.string().nullish(),
    successful: z.boolean().optional().default(true),
    created_at: z.iso.datetime()
});

/**
 * LoginHistoryListResponse
 */
export const zLoginHistoryListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zLoginHistoryEntryResponse)
});

/**
 * LoginInitResponse
 */
export const zLoginInitResponse = z.object({
    success: z.boolean().optional().default(true),
    verification_token: z.string(),
    message: z.string().optional().default('OTP sent to your email.'),
    debug_otp: z.string().nullish()
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string()
});

/**
 * LoginVerifyRequest
 */
export const zLoginVerifyRequest = z.object({
    token: z.string().min(1),
    code: z.string().length(6).regex(/^\d{6}$/)
});

/**
 * LoginVerifyResponse
 */
export const zLoginVerifyResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Login verified successfully.')
});

/**
 * LogoutRequest
 */
export const zLogoutRequest = z.object({
    refresh_token: z.string()
});

/**
 * LogoutResponse
 */
export const zLogoutResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Logged out successfully.')
});

/**
 * ParticipantLeaderboardResponse
 */
export const zParticipantLeaderboardResponse = z.object({
    user_id: z.uuid(),
    full_name: z.string().nullish(),
    alias: z.string().nullish(),
    profile_picture_url: z.string().nullish(),
    count: z.int()
});

/**
 * ProfileAvatarData
 */
export const zProfileAvatarData = z.object({
    user_id: z.uuid(),
    image: z.string(),
    profile_picture_url: z.string()
});

/**
 * ProfileAvatarUploadData
 */
export const zProfileAvatarUploadData = z.object({
    upload_url: z.string(),
    object_key: z.string(),
    public_url: z.string(),
    expires_in: z.int()
});

/**
 * ProfileAvatarUploadRequest
 */
export const zProfileAvatarUploadRequest = z.object({
    content_type: z.string().min(1).max(100)
});

/**
 * ProfileAvatarUploadResponse
 */
export const zProfileAvatarUploadResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Profile avatar upload URL generated. Use upload_url to PUT your image directly to storage.'),
    data: zProfileAvatarData,
    upload: zProfileAvatarUploadData,
    access_token: z.string()
});

/**
 * PurgeDeadJobsResponse
 */
export const zPurgeDeadJobsResponse = z.object({
    success: z.boolean().optional().default(true),
    deleted_count: z.int()
});

/**
 * RefreshTokenRequest
 */
export const zRefreshTokenRequest = z.object({
    refresh_token: z.string().min(1)
});

/**
 * RefreshTokenResponse
 */
export const zRefreshTokenResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Token refreshed successfully.')
});

/**
 * RegisterForSessionResponse
 */
export const zRegisterForSessionResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Successfully registered for event session.'),
    data: zEventParticipantRecordResponse
});

/**
 * RegisterRequest
 */
export const zRegisterRequest = z.object({
    email: z.email(),
    password: z.string().min(8),
    accepted_terms_and_privacy_policy: z.boolean()
});

/**
 * RegisterResponse
 */
export const zRegisterResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    email: z.string(),
    message: z.string().optional().default('Registration successful. Please verify your email.'),
    verification_token: z.string().nullish()
});

/**
 * ResendOtpRequest
 */
export const zResendOtpRequest = z.object({
    token: z.string().min(1)
});

/**
 * ResendOtpResponse
 */
export const zResendOtpResponse = z.object({
    success: z.boolean().optional().default(true),
    verification_token: z.string(),
    message: z.string().optional().default('A new OTP has been sent to your email.'),
    debug_otp: z.string().nullish()
});

/**
 * ResendVerificationRequest
 */
export const zResendVerificationRequest = z.object({
    email: z.email()
});

/**
 * ResendVerificationResponse
 */
export const zResendVerificationResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('If that email address is in our system and unverified, a new confirmation link has been sent.')
});

/**
 * ResetPasswordRequest
 */
export const zResetPasswordRequest = z.object({
    new_password: z.string().min(8)
});

/**
 * ResetPasswordResponse
 */
export const zResetPasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password has been reset successfully.')
});

/**
 * RetryJobResponse
 */
export const zRetryJobResponse = z.object({
    success: z.boolean().optional().default(true),
    original_job_id: z.string(),
    new_job_id: z.string(),
    function: z.string()
});

/**
 * ReviewApplicationRequest
 */
export const zReviewApplicationRequest = z.object({
    status: zApplicationStatus,
    contact_phone: z.string().min(7).max(20).nullish(),
    volunteer_role_id: z.uuid().nullish()
});

/**
 * RoleAction
 */
export const zRoleAction = z.enum([
    'create',
    'read',
    'update',
    'delete'
]);

/**
 * CreateGrantsRequest
 */
export const zCreateGrantsRequest = z.object({
    user_id: z.uuid(),
    role_id: z.uuid(),
    feature_id: z.uuid(),
    actions: z.array(zRoleAction).min(1),
    effect: zGrantEffect.optional().default('allow'),
    starts_at: z.iso.datetime().nullish(),
    expires_at: z.iso.datetime().nullish(),
    reason: z.string().max(500).nullish()
});

/**
 * RolePermissionRecordResponse
 */
export const zRolePermissionRecordResponse = z.object({
    feature_id: z.uuid(),
    feature_slug: z.string(),
    feature_name: z.string(),
    action: zRoleAction,
    effect: zGrantEffect
});

/**
 * RolePermissionRequest
 */
export const zRolePermissionRequest = z.object({
    feature_id: z.uuid(),
    actions: z.array(zRoleAction).min(1),
    effect: zGrantEffect.optional().default('allow')
});

/**
 * RoleCreateRequest
 */
export const zRoleCreateRequest = z.object({
    name: z.string().min(1).max(100),
    description: z.string().max(1000).nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRequest).optional()
});

/**
 * RolePermissionResponse
 */
export const zRolePermissionResponse = z.object({
    feature_slug: z.string(),
    feature_name: z.string(),
    action: zRoleAction,
    effect: zGrantEffect
});

/**
 * AssignableRoleResponse
 */
export const zAssignableRoleResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionResponse).optional()
});

/**
 * AssignableRoleListResponse
 */
export const zAssignableRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAssignableRoleResponse)
});

/**
 * ChangeUserRoleResponse
 */
export const zChangeUserRoleResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    role_id: z.uuid(),
    role_name: z.string(),
    permissions: z.array(zRolePermissionResponse).optional(),
    message: z.string().optional().default('User role updated successfully.')
});

/**
 * RoleRecordResponse
 */
export const zRoleRecordResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRecordResponse).optional()
});

/**
 * RoleListResponse
 */
export const zRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zRoleRecordResponse)
});

/**
 * RoleResponse
 */
export const zRoleResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zRoleRecordResponse,
    message: z.string().optional().default('Role saved successfully.')
});

/**
 * RoleUpdateRequest
 */
export const zRoleUpdateRequest = z.object({
    name: z.string().min(1).max(100),
    description: z.string().max(1000).nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRequest).optional()
});

/**
 * SendUserPasswordResetResponse
 */
export const zSendUserPasswordResetResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password reset link sent successfully.')
});

/**
 * SubmitAppFeedbackRequest
 */
export const zSubmitAppFeedbackRequest = z.object({
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(2000).nullish()
});

/**
 * SubmitAppFeedbackResponse
 */
export const zSubmitAppFeedbackResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Feedback submitted successfully'),
    data: zAppFeedbackRecordResponse
});

/**
 * SubmitApplicationRequest
 */
export const zSubmitApplicationRequest = z.object({
    application_data: z.record(z.string(), z.unknown()).nullish()
});

/**
 * UpdateAssignmentRequest
 */
export const zUpdateAssignmentRequest = z.object({
    expires_at: z.iso.datetime().nullable()
});

/**
 * UpdateEventVolunteerStatusRequest
 */
export const zUpdateEventVolunteerStatusRequest = z.object({
    status: zEventVolunteerStatus
});

/**
 * UpdateParticipantStatusRequest
 */
export const zUpdateParticipantStatusRequest = z.object({
    new_status: zEventParticipantStatus
});

/**
 * UpdateParticipantStatusResponse
 */
export const zUpdateParticipantStatusResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Participant status updated successfully.'),
    data: zEventParticipantRecordResponse
});

/**
 * UpdateProfileRequest
 */
export const zUpdateProfileRequest = z.object({
    alias: z.string().min(3).max(100),
    first_name: z.string().min(1).max(100),
    last_name: z.string().min(1).max(100),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().max(150).nullish(),
    bio: z.string().max(500).nullish()
});

/**
 * UpdateProfileResponse
 */
export const zUpdateProfileResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    alias: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    message: z.string().optional().default('Profile updated successfully.'),
    access_token: z.string()
});

/**
 * UpdateVolunteerRoleRequest
 */
export const zUpdateVolunteerRoleRequest = z.object({
    name: z.string().min(2).max(100).nullish(),
    description: z.string().max(500).nullish(),
    is_active: z.boolean().nullish()
});

/**
 * UserDetailsData
 */
export const zUserDetailsData = z.object({
    user_id: z.uuid(),
    email: z.string(),
    alias: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    image: z.string().nullish(),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    role: z.string().nullish(),
    events_attended: z.array(zAttendedEventResponse)
});

/**
 * UserDetailsResponse
 */
export const zUserDetailsResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('User details retrieved successfully.'),
    data: zUserDetailsData
});

/**
 * UserGrantResponse
 */
export const zUserGrantResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    feature_id: z.uuid(),
    role_id: z.uuid(),
    action: zRoleAction,
    effect: zGrantEffect,
    reason: z.string().nullable(),
    starts_at: z.iso.datetime().nullish(),
    expires_at: z.iso.datetime().nullish(),
    granted_by: z.uuid().nullable()
});

/**
 * CreateGrantsResponse
 */
export const zCreateGrantsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserGrantResponse),
    message: z.string().optional().default('Grants created successfully.')
});

/**
 * UserGrantListResponse
 */
export const zUserGrantListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserGrantResponse),
    total: z.int()
});

/**
 * UserOnboardingRequest
 */
export const zUserOnboardingRequest = z.object({
    alias: z.string().min(3).max(100),
    first_name: z.string().min(1).max(100),
    last_name: z.string().min(1).max(100),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().max(150).nullish(),
    bio: z.string().max(500).nullish()
});

/**
 * UserOnboardingResponse
 */
export const zUserOnboardingResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    alias: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    message: z.string().optional().default('Onboarding completed successfully.'),
    access_token: z.string()
});

/**
 * UserPermissionsResponse
 */
export const zUserPermissionsResponse = z.object({
    success: z.boolean().optional().default(true),
    permissions: z.record(z.string(), z.boolean())
});

/**
 * UserRegistrationWeekResponse
 */
export const zUserRegistrationWeekResponse = z.object({
    week_start: z.iso.datetime(),
    week_end: z.iso.datetime(),
    count: z.int()
});

/**
 * UserRoleAssignmentResponse
 */
export const zUserRoleAssignmentResponse = z.object({
    success: z.boolean().optional().default(true),
    id: z.uuid(),
    user_id: z.uuid(),
    role_id: z.uuid(),
    expires_at: z.iso.datetime().nullish(),
    assigned_by: z.uuid().nullable(),
    assigned_at: z.iso.datetime()
});

/**
 * UserRoleListResponse
 */
export const zUserRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserRoleAssignmentResponse),
    total: z.int()
});

/**
 * UserStatus
 */
export const zUserStatus = z.enum([
    'active',
    'inactive',
    'locked',
    'deleted'
]);

/**
 * AdminUserAccountDetailResponse
 */
export const zAdminUserAccountDetailResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    name: z.string(),
    email: z.string(),
    status: zUserStatus,
    role_id: z.uuid().nullish(),
    role_name: z.string().nullish(),
    alias: z.string().nullish(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    age_group: zAgeGroup.nullish(),
    gender: zGender.nullish(),
    education_level: zEducationLevel.nullish(),
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    onboarding_completed: z.boolean(),
    onboarding_completed_at: z.string().nullish(),
    email_verified: z.boolean(),
    email_verified_at: z.string().nullish(),
    password_change_at: z.string().nullish(),
    failed_login_attempts: z.int(),
    locked_until: z.string().nullish(),
    last_login_at: z.string().nullish(),
    last_activity_at: z.string().nullish(),
    login_count: z.int(),
    deletion_requested_at: z.string().nullish(),
    deletion_scheduled_for: z.string().nullish(),
    deletion_requested_by: z.uuid().nullish(),
    deletion_reason: z.string().nullish(),
    deleted_at: z.string().nullish(),
    created_at: z.string().nullish(),
    updated_at: z.string().nullish(),
    role_permissions: z.array(zRolePermissionResponse).optional()
});

/**
 * AdminUserAccountSummaryResponse
 */
export const zAdminUserAccountSummaryResponse = z.object({
    user_id: z.uuid(),
    name: z.string(),
    alias: z.string().nullish(),
    email: z.string(),
    role_id: z.uuid().nullish(),
    role_name: z.string().nullish(),
    status: zUserStatus,
    deletion_scheduled_for: z.string().nullish()
});

/**
 * AdminUserAccountListResponse
 */
export const zAdminUserAccountListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAdminUserAccountSummaryResponse),
    pagination: zAdminUserAccountPaginationResponse
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * ValidationErrorResponse
 */
export const zValidationErrorResponse = z.object({
    success: z.boolean().optional().default(false),
    detail: z.array(z.unknown())
});

/**
 * VenueCapacityData
 */
export const zVenueCapacityData = z.object({
    id: z.uuid(),
    name: z.string(),
    capacity: z.int()
});

/**
 * VenueCapacityResponse
 */
export const zVenueCapacityResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Venue capacity retrieved successfully.'),
    data: zVenueCapacityData
});

/**
 * VenueImageUploadData
 */
export const zVenueImageUploadData = z.object({
    upload_url: z.string(),
    object_key: z.string(),
    public_url: z.string(),
    expires_in: z.int()
});

/**
 * VenueImageUploadRequest
 */
export const zVenueImageUploadRequest = z.object({
    content_type: z.string().min(1).max(100)
});

/**
 * VenuePaginationResponse
 */
export const zVenuePaginationResponse = z.object({
    page: z.int(),
    page_size: z.int(),
    total_count: z.int(),
    total_pages: z.int(),
    has_next: z.boolean(),
    has_previous: z.boolean()
});

/**
 * VenueRatingAverageData
 */
export const zVenueRatingAverageData = z.object({
    venue_id: z.uuid(),
    average: z.number().nullable(),
    count: z.int()
});

/**
 * VenueRatingAverageResponse
 */
export const zVenueRatingAverageResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zVenueRatingAverageData
});

/**
 * VenueRatingCreateRequest
 */
export const zVenueRatingCreateRequest = z.object({
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(1000).nullish()
});

/**
 * VenueRatingDeleteResponse
 */
export const zVenueRatingDeleteResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Rating removed successfully.')
});

/**
 * VenueRatingPaginationResponse
 */
export const zVenueRatingPaginationResponse = z.object({
    page: z.int(),
    page_size: z.int(),
    total_count: z.int(),
    total_pages: z.int(),
    has_next: z.boolean(),
    has_previous: z.boolean()
});

/**
 * VenueRatingRecordResponse
 */
export const zVenueRatingRecordResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    venue_id: z.uuid(),
    rating: z.int(),
    comment: z.string().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * VenueRatingListResponse
 */
export const zVenueRatingListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zVenueRatingRecordResponse),
    pagination: zVenueRatingPaginationResponse
});

/**
 * VenueRatingResponse
 */
export const zVenueRatingResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zVenueRatingRecordResponse,
    message: z.string().optional().default('Rating saved successfully.')
});

/**
 * VenueRatingUpdateRequest
 */
export const zVenueRatingUpdateRequest = z.object({
    rating: z.int().gte(1).lte(5),
    comment: z.string().max(1000).nullish()
});

/**
 * VenueType
 */
export const zVenueType = z.enum([
    'indoor',
    'outdoor',
    'hybrid'
]);

/**
 * CommunityVenueCreateRequest
 *
 * Venue suggested by the community — contact information is optional.
 */
export const zCommunityVenueCreateRequest = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    image_url: z.string().max(512).nullish(),
    address_line: z.string().min(1).max(255),
    city: z.string().min(1).max(100),
    province: z.string().min(1).max(100),
    postal_code: z.string().min(1).max(20),
    region: z.string().min(1).max(100),
    country: z.string().min(1).max(100),
    capacity: z.int().gt(0),
    venue_type: zVenueType,
    amenities: z.array(z.string()).nullish(),
    contact_name: z.string().max(255).nullish(),
    contact_phone: z.string().max(20).nullish(),
    contact_email: z.email().nullish()
});

/**
 * OfficialVenueCreateRequest
 *
 * Officially managed venue — contact information is required.
 */
export const zOfficialVenueCreateRequest = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    image_url: z.string().max(512).nullish(),
    address_line: z.string().min(1).max(255),
    city: z.string().min(1).max(100),
    province: z.string().min(1).max(100),
    postal_code: z.string().min(1).max(20),
    region: z.string().min(1).max(100),
    country: z.string().min(1).max(100),
    capacity: z.int().gt(0),
    venue_type: zVenueType,
    amenities: z.array(z.string()).nullish(),
    contact_name: z.string().min(1).max(255),
    contact_phone: z.string().min(1).max(20),
    contact_email: z.email()
});

/**
 * PublicVenueRecordResponse
 */
export const zPublicVenueRecordResponse = z.object({
    id: z.uuid(),
    image_url: z.string().nullish(),
    name: z.string(),
    description: z.string().nullable(),
    address_line: z.string(),
    city: z.string(),
    province: z.string(),
    postal_code: z.string(),
    region: z.string(),
    country: z.string(),
    capacity: z.int(),
    venue_type: zVenueType,
    popularity_count: z.int(),
    usage_count: z.int(),
    is_partner: z.boolean(),
    amenities: z.array(z.string()).nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * PublicVenueListResponse
 */
export const zPublicVenueListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zPublicVenueRecordResponse),
    pagination: zVenuePaginationResponse
});

/**
 * PublicVenueResponse
 */
export const zPublicVenueResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zPublicVenueRecordResponse
});

/**
 * SuggestedVenueUpdateRequest
 */
export const zSuggestedVenueUpdateRequest = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    image_url: z.string().max(512).nullish(),
    address_line: z.string().min(1).max(255),
    city: z.string().min(1).max(100),
    province: z.string().min(1).max(100),
    postal_code: z.string().min(1).max(20),
    region: z.string().min(1).max(100),
    country: z.string().min(1).max(100),
    capacity: z.int().gt(0),
    venue_type: zVenueType,
    amenities: z.array(z.string()).nullish(),
    contact_name: z.string().max(255).nullish(),
    contact_phone: z.string().max(20).nullish(),
    contact_email: z.email().nullish()
});

/**
 * VenueRecordResponse
 */
export const zVenueRecordResponse = z.object({
    id: z.uuid(),
    creator_id: z.uuid(),
    image_url: z.string().nullish(),
    name: z.string(),
    description: z.string().nullable(),
    address_line: z.string(),
    city: z.string(),
    province: z.string(),
    postal_code: z.string(),
    region: z.string(),
    country: z.string(),
    capacity: z.int(),
    venue_type: zVenueType,
    popularity_count: z.int(),
    usage_count: z.int(),
    is_partner: z.boolean(),
    amenities: z.array(z.string()).nullable(),
    contact_name: z.string().nullable(),
    contact_phone: z.string().nullable(),
    contact_email: z.string().nullable(),
    created_at: z.iso.datetime().nullable(),
    updated_at: z.iso.datetime().nullable()
});

/**
 * VenueImageUploadResponse
 */
export const zVenueImageUploadResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Venue image upload URL generated. Use upload_url to PUT your image directly to storage.'),
    data: zVenueRecordResponse,
    upload: zVenueImageUploadData
});

/**
 * VenueListResponse
 */
export const zVenueListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zVenueRecordResponse),
    pagination: zVenuePaginationResponse
});

/**
 * VenueResponse
 */
export const zVenueResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zVenueRecordResponse,
    message: z.string().optional().default('Venue saved successfully.')
});

/**
 * VenueUpdateRequest
 */
export const zVenueUpdateRequest = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    image_url: z.string().max(512).nullish(),
    address_line: z.string().min(1).max(255),
    city: z.string().min(1).max(100),
    province: z.string().min(1).max(100),
    postal_code: z.string().min(1).max(20),
    region: z.string().min(1).max(100),
    country: z.string().min(1).max(100),
    capacity: z.int().gt(0),
    venue_type: zVenueType,
    is_partner: z.boolean().optional().default(false),
    amenities: z.array(z.string()).nullish(),
    contact_name: z.string().min(1).max(255),
    contact_phone: z.string().min(1).max(20),
    contact_email: z.email()
});

/**
 * VenueUsageResponse
 */
export const zVenueUsageResponse = z.object({
    venue_id: z.uuid(),
    name: z.string(),
    city: z.string().nullish(),
    province: z.string().nullish(),
    event_session_count: z.int()
});

/**
 * VerifyEmailResponse
 */
export const zVerifyEmailResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Email verified successfully.')
});

/**
 * VolunteerLeaderboardResponse
 */
export const zVolunteerLeaderboardResponse = z.object({
    volunteer_id: z.uuid().nullish(),
    user_id: z.uuid().nullish(),
    full_name: z.string().nullish(),
    alias: z.string().nullish(),
    profile_picture_url: z.string().nullish(),
    role_name: z.string().nullish(),
    count: z.int()
});

/**
 * DashboardMetricsResponse
 */
export const zDashboardMetricsResponse = z.object({
    recent_events: z.array(zEventSummaryResponse),
    ongoing_events: z.array(zEventSummaryResponse),
    upcoming_events: z.array(zEventSummaryResponse),
    top_weekly_participants: z.array(zParticipantLeaderboardResponse),
    top_weekly_volunteer_applications: z.array(zVolunteerLeaderboardResponse),
    top_active_volunteers: z.array(zVolunteerLeaderboardResponse),
    top_active_participants: z.array(zParticipantLeaderboardResponse),
    top_venues: z.array(zVenueUsageResponse),
    users_per_week: z.array(zUserRegistrationWeekResponse)
});

/**
 * DashboardDataResponse
 */
export const zDashboardDataResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Dashboard data retrieved successfully'),
    data: zDashboardMetricsResponse
});

/**
 * VolunteerStatus
 */
export const zVolunteerStatus = z.enum([
    'active',
    'inactive',
    'suspended'
]);

/**
 * UpdateVolunteerRequest
 */
export const zUpdateVolunteerRequest = z.object({
    contact_phone: z.string().min(7).max(20).nullish(),
    volunteer_role_id: z.uuid().nullish(),
    status: zVolunteerStatus.nullish()
});

/**
 * WeeklyRegistrationEntry
 */
export const zWeeklyRegistrationEntry = z.object({
    week_start: z.iso.datetime(),
    week_end: z.iso.datetime(),
    count: z.int()
});

/**
 * UsersPerWeekData
 */
export const zUsersPerWeekData = z.object({
    entries: z.array(zWeeklyRegistrationEntry),
    weeks: z.int()
});

/**
 * UsersPerWeekResponse
 */
export const zUsersPerWeekResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Weekly user registrations retrieved successfully'),
    data: zUsersPerWeekData
});

/**
 * WithdrawRegistrationResponse
 */
export const zWithdrawRegistrationResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Registration withdrawn successfully.'),
    data: zEventParticipantRecordResponse
});

/**
 * WorkerHealthEntrySchema
 */
export const zWorkerHealthEntrySchema = z.object({
    raw: z.string(),
    timestamp: z.string().nullable(),
    j_complete: z.int(),
    j_failed: z.int(),
    j_retried: z.int(),
    j_ongoing: z.int(),
    queued: z.int()
});

/**
 * QueueStatsResponse
 */
export const zQueueStatsResponse = z.object({
    success: z.boolean().optional().default(true),
    queue_name: z.string(),
    pending: z.int(),
    in_progress: z.int(),
    total_failed: z.int(),
    total_completed: z.int(),
    worker_health: z.array(zWorkerHealthEntrySchema)
});

/**
 * PaginationMeta
 */
export const zAppControllerSchemasAuditLogSchemaPaginationMeta = z.object({
    limit: z.int(),
    total_pages: z.int(),
    next_cursor: z.string().nullable(),
    prev_cursor: z.string().nullable(),
    has_next: z.boolean()
});

/**
 * GetAuditLogsResponse
 */
export const zGetAuditLogsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAuditLogResponse),
    pagination: zAppControllerSchemasAuditLogSchemaPaginationMeta
});

/**
 * PaginationMeta
 */
export const zAppControllerSchemasEventParticipantSchemaPaginationMeta = z.object({
    total: z.int(),
    limit: z.int(),
    offset: z.int()
});

/**
 * EventParticipantsResponse
 */
export const zEventParticipantsResponse = z.object({
    success: z.boolean(),
    message: z.string(),
    data: z.array(zEventParticipantRecord),
    meta: zAppControllerSchemasEventParticipantSchemaPaginationMeta
});

export const zListAppFeedbackAppFeedbackGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Successful Response
 */
export const zListAppFeedbackAppFeedbackGetResponse = zAppFeedbackListResponse;

export const zSubmitAppFeedbackAppFeedbackPostBody = zSubmitAppFeedbackRequest;

/**
 * Successful Response
 */
export const zSubmitAppFeedbackAppFeedbackPostResponse = zSubmitAppFeedbackResponse;

export const zGetUsersPerWeekAppFeedbackUsersPerWeekGetQuery = z.object({
    weeks: z.int().gte(1).lte(52).optional().default(12)
});

/**
 * Successful Response
 */
export const zGetUsersPerWeekAppFeedbackUsersPerWeekGetResponse = zUsersPerWeekResponse;

/**
 * Successful Response
 */
export const zGetDashboardDataDashboardGetResponse = zDashboardDataResponse;

export const zRegisterUserAuthRegisterPostBody = zRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterUserAuthRegisterPostResponse = zRegisterResponse;

export const zVerifyEmailAuthVerifyTokenGetPath = z.object({
    token: z.string().min(1)
});

/**
 * Successful Response
 */
export const zVerifyEmailAuthVerifyTokenGetResponse = zVerifyEmailResponse;

export const zResendVerificationAuthResendVerificationPostBody = zResendVerificationRequest;

/**
 * Successful Response
 */
export const zResendVerificationAuthResendVerificationPostResponse = zResendVerificationResponse;

export const zLoginAuthLoginPostBody = zLoginRequest;

/**
 * Successful Response
 */
export const zLoginAuthLoginPostResponse = zLoginInitResponse;

export const zLoginVerifyAuthLoginVerifyPostBody = zLoginVerifyRequest;

/**
 * Successful Response
 */
export const zLoginVerifyAuthLoginVerifyPostResponse = zLoginVerifyResponse;

export const zResendOtpAuthLoginResendOtpPostBody = zResendOtpRequest;

/**
 * Successful Response
 */
export const zResendOtpAuthLoginResendOtpPostResponse = zResendOtpResponse;

export const zLogoutAuthLogoutPostBody = zLogoutRequest;

/**
 * Successful Response
 */
export const zLogoutAuthLogoutPostResponse = zLogoutResponse;

export const zRefreshTokenAuthRefreshPostBody = zRefreshTokenRequest;

/**
 * Successful Response
 */
export const zRefreshTokenAuthRefreshPostResponse = zRefreshTokenResponse;

export const zForgotPasswordAuthForgotPasswordPostBody = zForgotPasswordRequest;

/**
 * Successful Response
 */
export const zForgotPasswordAuthForgotPasswordPostResponse = zForgotPasswordResponse;

export const zResetPasswordAuthResetPasswordTokenPostBody = zResetPasswordRequest;

export const zResetPasswordAuthResetPasswordTokenPostPath = z.object({
    token: z.string().min(1)
});

/**
 * Successful Response
 */
export const zResetPasswordAuthResetPasswordTokenPostResponse = zResetPasswordResponse;

/**
 * Successful Response
 */
export const zGetMyPermissionsUserMePermissionsGetResponse = zUserPermissionsResponse;

export const zCheckAliasUserCheckAliasGetQuery = z.object({
    alias: z.string().min(3).max(100)
});

/**
 * Successful Response
 */
export const zCheckAliasUserCheckAliasGetResponse = zCheckAliasResponse;

export const zUserOnboardingUserOnboardPostBody = zUserOnboardingRequest;

/**
 * Successful Response
 */
export const zUserOnboardingUserOnboardPostResponse = zUserOnboardingResponse;

export const zGetUserDetailsUserProfileGetQuery = z.object({
    attended_events_limit: z.int().gte(0).lte(50).optional().default(10)
});

/**
 * Successful Response
 */
export const zGetUserDetailsUserProfileGetResponse = zUserDetailsResponse;

export const zUpdateProfileUserProfilePatchBody = zUpdateProfileRequest;

/**
 * Successful Response
 */
export const zUpdateProfileUserProfilePatchResponse = zUpdateProfileResponse;

export const zGetEventsAttendedUserProfileEventsAttendedGetQuery = z.object({
    limit: z.int().gte(0).lte(50).optional().default(10)
});

/**
 * Successful Response
 */
export const zGetEventsAttendedUserProfileEventsAttendedGetResponse = zEventsAttendedResponse;

export const zUploadProfileAvatarUserProfileAvatarPatchBody = zProfileAvatarUploadRequest;

/**
 * Successful Response
 */
export const zUploadProfileAvatarUserProfileAvatarPatchResponse = zProfileAvatarUploadResponse;

export const zGetLoginHistoryUserLoginHistoryGetQuery = z.object({
    limit: z.int().gte(1).lte(50).optional().default(10)
});

/**
 * Successful Response
 */
export const zGetLoginHistoryUserLoginHistoryGetResponse = zLoginHistoryListResponse;

export const zChangePasswordUserChangePasswordPostBody = zChangePasswordRequest;

/**
 * Successful Response
 */
export const zChangePasswordUserChangePasswordPostResponse = zChangePasswordResponse;

export const zScheduleOwnAccountDeletionUserAccountDeletionPostBody = zDeleteAccountRequest;

/**
 * Successful Response
 */
export const zScheduleOwnAccountDeletionUserAccountDeletionPostResponse = zDeleteAccountResponse;

/**
 * Successful Response
 */
export const zListRolesUserAccountsRolesGetResponse = zAssignableRoleListResponse;

export const zListUserAccountsUserAccountsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10),
    search: z.string().max(200).nullish(),
    status: zUserStatus.nullish(),
    role: z.string().nullish()
});

/**
 * Successful Response
 */
export const zListUserAccountsUserAccountsGetResponse = zAdminUserAccountListResponse;

export const zGetUserAccountDetailUserAccountsUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetUserAccountDetailUserAccountsUserIdGetResponse = zAdminUserAccountDetailResponse;

export const zChangeUserRoleUserAccountsUserIdRolePatchBody = zChangeUserRoleRequest;

export const zChangeUserRoleUserAccountsUserIdRolePatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChangeUserRoleUserAccountsUserIdRolePatchResponse = zChangeUserRoleResponse;

export const zChangeUserEmailUserAccountsUserIdEmailPatchBody = zChangeUserEmailRequest;

export const zChangeUserEmailUserAccountsUserIdEmailPatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChangeUserEmailUserAccountsUserIdEmailPatchResponse = zChangeUserEmailResponse;

export const zSendUserPasswordResetUserAccountsUserIdPasswordResetPostPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zSendUserPasswordResetUserAccountsUserIdPasswordResetPostResponse = zSendUserPasswordResetResponse;

export const zScheduleAdminAccountDeletionUserAccountsUserIdAccountDeletionPostBody = zAdminDeleteAccountRequest;

export const zScheduleAdminAccountDeletionUserAccountsUserIdAccountDeletionPostPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zScheduleAdminAccountDeletionUserAccountsUserIdAccountDeletionPostResponse = zDeleteAccountResponse;

export const zGetAuditLogsAuditLogsGetQuery = z.object({
    limit: z.int().gte(10).lte(100).optional().default(10),
    cursor: z.string().nullish(),
    user_id: z.uuid().nullish(),
    action_type: zActionType.nullish(),
    resource_type: z.string().nullish(),
    start_date: z.iso.datetime().nullish(),
    end_date: z.iso.datetime().nullish()
});

/**
 * Successful Response
 */
export const zGetAuditLogsAuditLogsGetResponse = zGetAuditLogsResponse;

/**
 * Successful Response
 */
export const zListFeaturesFeaturesGetResponse = zFeatureListResponse;

export const zCreateFeatureFeaturesPostBody = zFeatureCreateRequest;

/**
 * Successful Response
 */
export const zCreateFeatureFeaturesPostResponse = zFeatureResponse;

export const zDeleteFeatureFeaturesFeatureIdDeletePath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteFeatureFeaturesFeatureIdDeleteResponse = z.void();

export const zGetFeatureFeaturesFeatureIdGetPath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetFeatureFeaturesFeatureIdGetResponse = zFeatureResponse;

export const zUpdateFeatureFeaturesFeatureIdPatchBody = zFeatureUpdateRequest;

export const zUpdateFeatureFeaturesFeatureIdPatchPath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateFeatureFeaturesFeatureIdPatchResponse = zFeatureResponse;

/**
 * Successful Response
 */
export const zListRolesRolesGetResponse = zRoleListResponse;

export const zCreateRoleRolesPostBody = zRoleCreateRequest;

/**
 * Successful Response
 */
export const zCreateRoleRolesPostResponse = zRoleResponse;

export const zDeleteRoleRolesRoleIdDeletePath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteRoleRolesRoleIdDeleteResponse = z.void();

export const zGetRoleRolesRoleIdGetPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetRoleRolesRoleIdGetResponse = zRoleResponse;

export const zUpdateRoleRolesRoleIdPatchBody = zRoleUpdateRequest;

export const zUpdateRoleRolesRoleIdPatchPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateRoleRolesRoleIdPatchResponse = zRoleResponse;

export const zListUserRolesUserRolesGetQuery = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListUserRolesUserRolesGetResponse = zUserRoleListResponse;

export const zAssignRoleUserRolesPostBody = zAssignRoleRequest;

/**
 * Successful Response
 */
export const zAssignRoleUserRolesPostResponse = zUserRoleAssignmentResponse;

export const zRevokeAssignmentUserRolesAssignmentIdDeletePath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeAssignmentUserRolesAssignmentIdDeleteResponse = z.void();

export const zGetAssignmentUserRolesAssignmentIdGetPath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAssignmentUserRolesAssignmentIdGetResponse = zUserRoleAssignmentResponse;

export const zUpdateAssignmentUserRolesAssignmentIdPatchBody = zUpdateAssignmentRequest;

export const zUpdateAssignmentUserRolesAssignmentIdPatchPath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAssignmentUserRolesAssignmentIdPatchResponse = zUserRoleAssignmentResponse;

export const zListUserGrantsUserGrantsGetQuery = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListUserGrantsUserGrantsGetResponse = zUserGrantListResponse;

export const zCreateGrantsUserGrantsPostBody = zCreateGrantsRequest;

/**
 * Successful Response
 */
export const zCreateGrantsUserGrantsPostResponse = zCreateGrantsResponse;

/**
 * Successful Response
 */
export const zListGrantFeaturesUserGrantsFeaturesGetResponse = zGrantFeatureListResponse;

export const zRevokeGrantUserGrantsGrantIdDeletePath = z.object({
    grant_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeGrantUserGrantsGrantIdDeleteResponse = z.void();

/**
 * Successful Response
 */
export const zGetQueueStatsQueuesGetResponse = zQueueStatsResponse;

/**
 * Successful Response
 */
export const zPurgeDeadJobsQueuesDlqDeleteResponse = zPurgeDeadJobsResponse;

export const zListDeadJobsQueuesDlqGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    limit: z.int().gte(1).lte(100).optional().default(10)
});

/**
 * Successful Response
 */
export const zListDeadJobsQueuesDlqGetResponse = zListDeadJobsResponse;

export const zRetryDeadJobQueuesDlqJobIdRetryPostPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zRetryDeadJobQueuesDlqJobIdRetryPostResponse = zRetryJobResponse;

export const zDeleteDeadJobQueuesDlqJobIdDeletePath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteDeadJobQueuesDlqJobIdDeleteResponse = zDeleteJobResponse;

export const zListPartnerVenuesVenuesPublicPartnersGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10),
    search: z.string().max(200).nullish(),
    venue_type: zVenueType.nullish()
});

/**
 * Successful Response
 */
export const zListPartnerVenuesVenuesPublicPartnersGetResponse = zPublicVenueListResponse;

export const zGetPartnerVenueVenuesPublicPartnersVenueIdGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetPartnerVenueVenuesPublicPartnersVenueIdGetResponse = zPublicVenueResponse;

export const zListCommunityVenuesVenuesPublicCommunityGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10),
    search: z.string().max(200).nullish(),
    venue_type: zVenueType.nullish()
});

/**
 * Successful Response
 */
export const zListCommunityVenuesVenuesPublicCommunityGetResponse = zPublicVenueListResponse;

export const zGetCommunityVenueVenuesPublicCommunityVenueIdGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetCommunityVenueVenuesPublicCommunityVenueIdGetResponse = zPublicVenueResponse;

export const zListVenuesVenuesGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10),
    search: z.string().max(200).nullish(),
    venue_type: zVenueType.nullish(),
    is_partner: z.boolean().nullish()
});

/**
 * Successful Response
 */
export const zListVenuesVenuesGetResponse = zVenueListResponse;

export const zDeleteVenueVenuesVenueIdDeletePath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteVenueVenuesVenueIdDeleteResponse = z.void();

export const zGetVenueVenuesVenueIdGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetVenueVenuesVenueIdGetResponse = zVenueResponse;

export const zUpdateVenueVenuesVenueIdPatchBody = zVenueUpdateRequest;

export const zUpdateVenueVenuesVenueIdPatchPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateVenueVenuesVenueIdPatchResponse = zVenueResponse;

export const zGetVenueCapacityVenuesVenueIdCapacityGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetVenueCapacityVenuesVenueIdCapacityGetResponse = zVenueCapacityResponse;

export const zCreateCommunityVenueVenuesCommunityPostBody = zCommunityVenueCreateRequest;

/**
 * Successful Response
 */
export const zCreateCommunityVenueVenuesCommunityPostResponse = zVenueResponse;

export const zDeleteSuggestedVenueVenuesCommunityVenueIdDeletePath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteSuggestedVenueVenuesCommunityVenueIdDeleteResponse = z.void();

export const zUpdateSuggestedVenueVenuesCommunityVenueIdPatchBody = zSuggestedVenueUpdateRequest;

export const zUpdateSuggestedVenueVenuesCommunityVenueIdPatchPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateSuggestedVenueVenuesCommunityVenueIdPatchResponse = zVenueResponse;

export const zCreateOfficialVenueVenuesOfficialPostBody = zOfficialVenueCreateRequest;

/**
 * Successful Response
 */
export const zCreateOfficialVenueVenuesOfficialPostResponse = zVenueResponse;

export const zUploadVenueImageVenuesVenueIdImagePostBody = zVenueImageUploadRequest;

export const zUploadVenueImageVenuesVenueIdImagePostPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUploadVenueImageVenuesVenueIdImagePostResponse = zVenueImageUploadResponse;

export const zListVenueRatingsVenuesVenueIdRatingsGetPath = z.object({
    venue_id: z.uuid()
});

export const zListVenueRatingsVenuesVenueIdRatingsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10)
});

/**
 * Successful Response
 */
export const zListVenueRatingsVenuesVenueIdRatingsGetResponse = zVenueRatingListResponse;

export const zCreateVenueRatingVenuesVenueIdRatingsPostBody = zVenueRatingCreateRequest;

export const zCreateVenueRatingVenuesVenueIdRatingsPostPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateVenueRatingVenuesVenueIdRatingsPostResponse = zVenueRatingResponse;

export const zGetVenueRatingAverageVenuesVenueIdRatingsAverageGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetVenueRatingAverageVenuesVenueIdRatingsAverageGetResponse = zVenueRatingAverageResponse;

export const zDeleteMyVenueRatingVenuesVenueIdRatingsMeDeletePath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteMyVenueRatingVenuesVenueIdRatingsMeDeleteResponse = zVenueRatingDeleteResponse;

export const zGetMyVenueRatingVenuesVenueIdRatingsMeGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetMyVenueRatingVenuesVenueIdRatingsMeGetResponse = zVenueRatingResponse;

export const zUpdateMyVenueRatingVenuesVenueIdRatingsMePatchBody = zVenueRatingUpdateRequest;

export const zUpdateMyVenueRatingVenuesVenueIdRatingsMePatchPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateMyVenueRatingVenuesVenueIdRatingsMePatchResponse = zVenueRatingResponse;

export const zGetAllEventsEventsGetQuery = z.object({
    status: zEventStatus.nullish(),
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20)
});

/**
 * Paginated list of events
 */
export const zGetAllEventsEventsGetResponse = zEventListResponse;

export const zCreateEventEventsPostBody = zEventCreateRequest;

/**
 * Successful Response
 */
export const zCreateEventEventsPostResponse = zEventWithSessionsResponse;

export const zDeleteEventEventsEventIdDeletePath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteEventEventsEventIdDeleteResponse = zEventDeletedResponse;

export const zGetEventWithSessionsEventsEventIdGetPath = z.object({
    event_id: z.uuid()
});

/**
 * Event with all its sessions
 */
export const zGetEventWithSessionsEventsEventIdGetResponse = zEventDetailResponse;

export const zUpdateEventMetadataEventsEventIdPatchBody = zEventUpdateRequest;

export const zUpdateEventMetadataEventsEventIdPatchPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateEventMetadataEventsEventIdPatchResponse = zEventMetadataUpdatedResponse;

export const zDeleteEventSessionEventsEventIdSessionSessionIdDeletePath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteEventSessionEventsEventIdSessionSessionIdDeleteResponse = zEventSessionDeletedResponse;

export const zUpdateEventSessionEventsEventIdSessionSessionIdPatchBody = zEventSessionUpdateRequest;

export const zUpdateEventSessionEventsEventIdSessionSessionIdPatchPath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateEventSessionEventsEventIdSessionSessionIdPatchResponse = zEventSessionUpdatedResponse;

export const zCreateEventSessionEventsEventIdSessionPostBody = zEventSessionCreateRequest;

export const zCreateEventSessionEventsEventIdSessionPostPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateEventSessionEventsEventIdSessionPostResponse = zEventSessionCreatedResponse;

export const zUpdateEventStatusEventsEventIdStatusPatchBody = zEventStatusUpdateRequest;

export const zUpdateEventStatusEventsEventIdStatusPatchPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateEventStatusEventsEventIdStatusPatchResponse = zEventStatusUpdatedResponse;

export const zUpdateEventSessionStatusEventsEventIdSessionSessionIdStatusPatchBody = zEventSessionStatusUpdateRequest;

export const zUpdateEventSessionStatusEventsEventIdSessionSessionIdStatusPatchPath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateEventSessionStatusEventsEventIdSessionSessionIdStatusPatchResponse = zEventSessionStatusUpdatedResponse;

export const zUploadEventBannerEventsEventIdBannerPostBody = zEventBannerUploadRequest;

export const zUploadEventBannerEventsEventIdBannerPostPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUploadEventBannerEventsEventIdBannerPostResponse = zEventBannerUploadResponse;

export const zListEventFeedbackEventsEventIdFeedbackGetPath = z.object({
    event_id: z.uuid()
});

export const zListEventFeedbackEventsEventIdFeedbackGetQuery = z.object({
    limit: z.int().gte(1).lte(100).optional().default(20),
    offset: z.int().gte(0).optional().default(0)
});

/**
 * Successful Response
 */
export const zListEventFeedbackEventsEventIdFeedbackGetResponse = zEventFeedbackListResponse;

export const zCreateEventFeedbackEventsEventIdFeedbackPostBody = zCreateEventFeedbackRequest;

export const zCreateEventFeedbackEventsEventIdFeedbackPostPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCreateEventFeedbackEventsEventIdFeedbackPostResponse = zEventFeedbackResponse;

export const zGetEventParticipantsEventsEventIdParticipantsGetPath = z.object({
    event_id: z.uuid()
});

export const zGetEventParticipantsEventsEventIdParticipantsGetQuery = z.object({
    status: z.string().nullish(),
    limit: z.int().gte(1).lte(200).optional().default(50),
    offset: z.int().gte(0).optional().default(0)
});

/**
 * Successful Response
 */
export const zGetEventParticipantsEventsEventIdParticipantsGetResponse = zEventParticipantsResponse;

export const zWithdrawRegistrationEventsEventIdSessionSessionIdRegisterDeletePath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zWithdrawRegistrationEventsEventIdSessionSessionIdRegisterDeleteResponse = zWithdrawRegistrationResponse;

export const zRegisterForSessionEventsEventIdSessionSessionIdRegisterPostPath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRegisterForSessionEventsEventIdSessionSessionIdRegisterPostResponse = zRegisterForSessionResponse;

export const zUpdateParticipantStatusEventsEventIdSessionSessionIdParticipantsParticipantIdPatchBody = zUpdateParticipantStatusRequest;

export const zUpdateParticipantStatusEventsEventIdSessionSessionIdParticipantsParticipantIdPatchPath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid(),
    participant_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateParticipantStatusEventsEventIdSessionSessionIdParticipantsParticipantIdPatchResponse = zUpdateParticipantStatusResponse;

export const zCheckInParticipantEventsEventIdSessionSessionIdParticipantsParticipantIdCheckInPatchPath = z.object({
    event_id: z.uuid(),
    session_id: z.uuid(),
    participant_id: z.uuid()
});

/**
 * Successful Response
 */
export const zCheckInParticipantEventsEventIdSessionSessionIdParticipantsParticipantIdCheckInPatchResponse = zCheckInParticipantResponse;

export const zCheckInParticipantQrCodeEventsParticipantsCheckInQrPostBody = zCheckInParticipantQrCodeRequest;

/**
 * Successful Response
 */
export const zCheckInParticipantQrCodeEventsParticipantsCheckInQrPostResponse = zCheckInParticipantResponse;

export const zGetAllVolunteersVolunteersGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20),
    status: zVolunteerStatus.nullish(),
    role_id: z.uuid().nullish()
});

/**
 * Response Get All Volunteers Volunteers Get
 *
 * Successful Response
 */
export const zGetAllVolunteersVolunteersGetResponse = z.record(z.string(), z.unknown());

export const zAddVolunteerVolunteersPostBody = zAddVolunteerRequest;

/**
 * Response Add Volunteer Volunteers Post
 *
 * Successful Response
 */
export const zAddVolunteerVolunteersPostResponse = z.record(z.string(), z.unknown());

export const zGetPotentialVolunteersVolunteersPotentialGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20),
    min_events: z.int().gte(1).optional().default(1),
    search: z.string().max(100).nullish()
});

/**
 * Response Get Potential Volunteers Volunteers Potential Get
 *
 * Successful Response
 */
export const zGetPotentialVolunteersVolunteersPotentialGetResponse = z.record(z.string(), z.unknown());

export const zUpdateVolunteerInfoVolunteersVolunteerIdPatchBody = zUpdateVolunteerRequest;

export const zUpdateVolunteerInfoVolunteersVolunteerIdPatchPath = z.object({
    volunteer_id: z.uuid()
});

/**
 * Response Update Volunteer Info Volunteers  Volunteer Id  Patch
 *
 * Successful Response
 */
export const zUpdateVolunteerInfoVolunteersVolunteerIdPatchResponse = z.record(z.string(), z.unknown());

export const zGetAllVolunteerRolesVolunteerRolesGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(20),
    search: z.string().max(100).nullish(),
    is_active: z.boolean().nullish()
});

/**
 * Response Get All Volunteer Roles Volunteer Roles Get
 *
 * Successful Response
 */
export const zGetAllVolunteerRolesVolunteerRolesGetResponse = z.record(z.string(), z.unknown());

export const zCreateVolunteerRoleVolunteerRolesPostBody = zCreateVolunteerRoleRequest;

/**
 * Response Create Volunteer Role Volunteer Roles Post
 *
 * Successful Response
 */
export const zCreateVolunteerRoleVolunteerRolesPostResponse = z.record(z.string(), z.unknown());

export const zDeleteVolunteerRoleVolunteerRolesRoleIdDeletePath = z.object({
    role_id: z.uuid()
});

/**
 * Response Delete Volunteer Role Volunteer Roles  Role Id  Delete
 *
 * Successful Response
 */
export const zDeleteVolunteerRoleVolunteerRolesRoleIdDeleteResponse = z.record(z.string(), z.unknown());

export const zUpdateVolunteerRoleVolunteerRolesRoleIdPatchBody = zUpdateVolunteerRoleRequest;

export const zUpdateVolunteerRoleVolunteerRolesRoleIdPatchPath = z.object({
    role_id: z.uuid()
});

/**
 * Response Update Volunteer Role Volunteer Roles  Role Id  Patch
 *
 * Successful Response
 */
export const zUpdateVolunteerRoleVolunteerRolesRoleIdPatchResponse = z.record(z.string(), z.unknown());

export const zSubmitApplicationVolunteerApplicationsPostBody = zSubmitApplicationRequest;

/**
 * Response Submit Application Volunteer Applications Post
 *
 * Successful Response
 */
export const zSubmitApplicationVolunteerApplicationsPostResponse = z.record(z.string(), z.unknown());

export const zReviewApplicationVolunteerApplicationsApplicationIdReviewPatchBody = zReviewApplicationRequest;

export const zReviewApplicationVolunteerApplicationsApplicationIdReviewPatchPath = z.object({
    application_id: z.uuid()
});

/**
 * Response Review Application Volunteer Applications  Application Id  Review Patch
 *
 * Successful Response
 */
export const zReviewApplicationVolunteerApplicationsApplicationIdReviewPatchResponse = z.record(z.string(), z.unknown());

export const zWithdrawApplicationVolunteerApplicationsApplicationIdDeletePath = z.object({
    application_id: z.uuid()
});

/**
 * Response Withdraw Application Volunteer Applications  Application Id  Delete
 *
 * Successful Response
 */
export const zWithdrawApplicationVolunteerApplicationsApplicationIdDeleteResponse = z.record(z.string(), z.unknown());

/**
 * Body
 */
export const zApplyToEventEventsEventIdVolunteersApplyPostBody = zApplyEventVolunteerRequest.nullable();

export const zApplyToEventEventsEventIdVolunteersApplyPostPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zApplyToEventEventsEventIdVolunteersApplyPostResponse = zEventVolunteerResponse;

export const zListEventVolunteersEventsEventIdVolunteersGetPath = z.object({
    event_id: z.uuid()
});

export const zListEventVolunteersEventsEventIdVolunteersGetQuery = z.object({
    status: zEventVolunteerStatus.nullish()
});

/**
 * Successful Response
 */
export const zListEventVolunteersEventsEventIdVolunteersGetResponse = zEventVolunteerListResponse;

export const zAssignVolunteerEventsEventIdVolunteersPostBody = zAssignVolunteerRequest;

export const zAssignVolunteerEventsEventIdVolunteersPostPath = z.object({
    event_id: z.uuid()
});

/**
 * Successful Response
 */
export const zAssignVolunteerEventsEventIdVolunteersPostResponse = zEventVolunteerResponse;

export const zRemoveEventVolunteerEventsEventIdVolunteersEventVolunteerIdDeletePath = z.object({
    event_id: z.uuid(),
    event_volunteer_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRemoveEventVolunteerEventsEventIdVolunteersEventVolunteerIdDeleteResponse = zEventVolunteerResponse;

export const zUpdateEventVolunteerStatusEventsEventIdVolunteersEventVolunteerIdPatchBody = zUpdateEventVolunteerStatusRequest;

export const zUpdateEventVolunteerStatusEventsEventIdVolunteersEventVolunteerIdPatchPath = z.object({
    event_id: z.uuid(),
    event_volunteer_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateEventVolunteerStatusEventsEventIdVolunteersEventVolunteerIdPatchResponse = zEventVolunteerResponse;
