// This file is auto-generated by @hey-api/openapi-ts

import * as z from 'zod';

/**
 * ActionType
 */
export const zActionType = z.enum([
    'create',
    'read',
    'update',
    'delete',
    'login',
    'logout',
    'verify',
    'export',
    'import'
]);

/**
 * AdminDeleteAccountRequest
 */
export const zAdminDeleteAccountRequest = z.object({
    reason: z.string().min(1).max(500)
});

/**
 * AdminUserAccountPaginationResponse
 */
export const zAdminUserAccountPaginationResponse = z.object({
    page: z.int(),
    page_size: z.int(),
    total_count: z.int(),
    total_pages: z.int(),
    has_next: z.boolean(),
    has_previous: z.boolean()
});

/**
 * AgeGroup
 */
export const zAgeGroup = z.enum([
    'child',
    'teen',
    'adult',
    'senior'
]);

/**
 * AssignRoleRequest
 */
export const zAssignRoleRequest = z.object({
    user_id: z.uuid(),
    role_id: z.uuid(),
    expires_at: z.iso.datetime().nullish()
});

/**
 * AuditLogStatus
 */
export const zAuditLogStatus = z.enum(['success', 'failure']);

/**
 * AuditLogResponse
 */
export const zAuditLogResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid().nullable(),
    ip_address: z.string().nullable(),
    user_agent: z.string().nullable(),
    timestamp: z.iso.datetime(),
    action_type: zActionType,
    resource_type: z.string(),
    resource_id: z.string().nullable(),
    status: zAuditLogStatus,
    old_values: z.record(z.string(), z.unknown()).nullable(),
    new_values: z.record(z.string(), z.unknown()).nullable(),
    additional_context: z.record(z.string(), z.unknown()).nullable()
});

/**
 * ChangePasswordRequest
 */
export const zChangePasswordRequest = z.object({
    current_password: z.string().min(1),
    new_password: z.string().min(8)
});

/**
 * ChangePasswordResponse
 */
export const zChangePasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password changed successfully. All active sessions have been invalidated.')
});

/**
 * ChangeUserEmailRequest
 */
export const zChangeUserEmailRequest = z.object({
    email: z.email()
});

/**
 * ChangeUserEmailResponse
 */
export const zChangeUserEmailResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    email: z.email(),
    message: z.string().optional().default('User email updated successfully. A new verification link has been sent.')
});

/**
 * ChangeUserRoleRequest
 */
export const zChangeUserRoleRequest = z.object({
    role_id: z.uuid()
});

/**
 * CheckAliasResponse
 */
export const zCheckAliasResponse = z.object({
    success: z.boolean().optional().default(true),
    alias: z.string(),
    available: z.boolean()
});

/**
 * CreateVenueRequest
 */
export const zCreateVenueRequest = z.object({
    name: z.string().min(1).max(255),
    description: z.string().nullish(),
    address_line: z.string().min(1).max(255),
    city: z.string().min(1).max(100),
    province: z.string().min(1).max(100),
    postal_code: z.string().min(1).max(20),
    region: z.string().min(1).max(100),
    country: z.string().min(1).max(100),
    capacity: z.int().gt(0),
    venue_type: z.string(),
    contact_name: z.string().min(1).max(255),
    contact_phone: z.string().min(1).max(20),
    contact_email: z.string().min(1).max(255)
});

/**
 * CreateVenueResponse
 */
export const zCreateVenueResponse = z.object({
    success: z.boolean().optional().default(true),
    venue_id: z.uuid(),
    name: z.string(),
    message: z.string().optional().default('Venue created successfully.')
});

/**
 * DeadJobResponse
 */
export const zDeadJobResponse = z.object({
    job_id: z.string(),
    function: z.string(),
    args: z.array(z.unknown()),
    kwargs: z.record(z.string(), z.unknown()),
    job_try: z.int(),
    enqueue_time: z.iso.datetime(),
    finish_time: z.iso.datetime().nullable(),
    error: z.string()
});

/**
 * DeleteAccountRequest
 */
export const zDeleteAccountRequest = z.object({
    current_password: z.string().min(1),
    reason: z.string().min(1).max(500).nullish()
});

/**
 * DeleteAccountResponse
 */
export const zDeleteAccountResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    deletion_requested_at: z.iso.datetime(),
    deletion_scheduled_for: z.iso.datetime(),
    requested_by: z.uuid(),
    grace_period_days: z.int().optional().default(30),
    message: z.string().optional().default('Account deletion scheduled. The account will be permanently deleted after the 30-day grace period unless the user logs in before then.')
});

/**
 * DeleteJobResponse
 */
export const zDeleteJobResponse = z.object({
    success: z.boolean().optional().default(true),
    job_id: z.string(),
    deleted: z.boolean()
});

/**
 * EducationLevel
 */
export const zEducationLevel = z.enum([
    'no_formal_education',
    'elementary_level',
    'elementary_graduate',
    'junior_high_school_level',
    'junior_high_school_graduate',
    'senior_high_school_level',
    'senior_high_school_graduate',
    'vocational_trade_certificate',
    'college_level_undergraduate',
    'associate_degree',
    'bachelors_degree',
    'masters_degree',
    'doctorate_degree'
]);

/**
 * ErrorResponse
 */
export const zErrorResponse = z.object({
    success: z.boolean().optional().default(false),
    message: z.string()
});

/**
 * FeatureCreateRequest
 */
export const zFeatureCreateRequest = z.object({
    slug: z.string().min(1).max(100),
    name: z.string().min(1).max(150),
    description: z.string().max(1000).nullish(),
    is_enabled: z.boolean().optional().default(true)
});

/**
 * FeatureRecordResponse
 */
export const zFeatureRecordResponse = z.object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    is_enabled: z.boolean()
});

/**
 * FeatureListResponse
 */
export const zFeatureListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zFeatureRecordResponse)
});

/**
 * FeatureResponse
 */
export const zFeatureResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zFeatureRecordResponse,
    message: z.string().optional().default('Feature saved successfully.')
});

/**
 * FeatureUpdateRequest
 */
export const zFeatureUpdateRequest = z.object({
    slug: z.string().min(1).max(100),
    name: z.string().min(1).max(150),
    description: z.string().max(1000).nullish(),
    is_enabled: z.boolean().optional().default(true)
});

/**
 * ForgotPasswordRequest
 */
export const zForgotPasswordRequest = z.object({
    email: z.email()
});

/**
 * ForgotPasswordResponse
 */
export const zForgotPasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('If that email address is in our system, you will receive a password reset link shortly.')
});

/**
 * Gender
 */
export const zGender = z.enum(['male', 'female']);

/**
 * GrantEffect
 */
export const zGrantEffect = z.enum(['allow', 'deny']);

/**
 * GrantFeatureResponse
 */
export const zGrantFeatureResponse = z.object({
    id: z.uuid(),
    slug: z.string(),
    name: z.string(),
    description: z.string().nullish(),
    is_enabled: z.boolean()
});

/**
 * GrantFeatureListResponse
 */
export const zGrantFeatureListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zGrantFeatureResponse)
});

/**
 * ListDeadJobsResponse
 */
export const zListDeadJobsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zDeadJobResponse),
    total: z.int()
});

/**
 * LoginHistoryEntryResponse
 */
export const zLoginHistoryEntryResponse = z.object({
    id: z.uuid(),
    ip_address: z.string().nullish(),
    user_agent: z.string().nullish(),
    browser: z.string().nullish(),
    os: z.string().nullish(),
    device_type: z.string().nullish(),
    city: z.string().nullish(),
    region: z.string().nullish(),
    country: z.string().nullish(),
    successful: z.boolean().optional().default(true),
    created_at: z.iso.datetime()
});

/**
 * LoginHistoryListResponse
 */
export const zLoginHistoryListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zLoginHistoryEntryResponse)
});

/**
 * LoginInitResponse
 */
export const zLoginInitResponse = z.object({
    success: z.boolean().optional().default(true),
    verification_token: z.string(),
    message: z.string().optional().default('OTP sent to your email.'),
    debug_otp: z.string().nullish()
});

/**
 * LoginRequest
 */
export const zLoginRequest = z.object({
    email: z.email(),
    password: z.string()
});

/**
 * LoginVerifyRequest
 */
export const zLoginVerifyRequest = z.object({
    token: z.string().min(1),
    code: z.string().length(6).regex(/^\d{6}$/)
});

/**
 * LoginVerifyResponse
 */
export const zLoginVerifyResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Login verified successfully.')
});

/**
 * LogoutRequest
 */
export const zLogoutRequest = z.object({
    refresh_token: z.string()
});

/**
 * LogoutResponse
 */
export const zLogoutResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Logged out successfully.')
});

/**
 * PaginationMeta
 */
export const zPaginationMeta = z.object({
    limit: z.int(),
    total_pages: z.int(),
    next_cursor: z.string().nullable(),
    prev_cursor: z.string().nullable(),
    has_next: z.boolean()
});

/**
 * GetAuditLogsResponse
 */
export const zGetAuditLogsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAuditLogResponse),
    pagination: zPaginationMeta
});

/**
 * PurgeDeadJobsResponse
 */
export const zPurgeDeadJobsResponse = z.object({
    success: z.boolean().optional().default(true),
    deleted_count: z.int()
});

/**
 * RefreshTokenRequest
 */
export const zRefreshTokenRequest = z.object({
    refresh_token: z.string().min(1)
});

/**
 * RefreshTokenResponse
 */
export const zRefreshTokenResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Token refreshed successfully.')
});

/**
 * RegisterRequest
 */
export const zRegisterRequest = z.object({
    email: z.email(),
    password: z.string().min(8),
    accepted_terms_and_privacy_policy: z.boolean()
});

/**
 * RegisterResponse
 */
export const zRegisterResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    email: z.string(),
    message: z.string().optional().default('Registration successful. Please verify your email.'),
    verification_token: z.string().nullish()
});

/**
 * ResendOtpRequest
 */
export const zResendOtpRequest = z.object({
    token: z.string().min(1)
});

/**
 * ResendOtpResponse
 */
export const zResendOtpResponse = z.object({
    success: z.boolean().optional().default(true),
    verification_token: z.string(),
    message: z.string().optional().default('A new OTP has been sent to your email.'),
    debug_otp: z.string().nullish()
});

/**
 * ResendVerificationRequest
 */
export const zResendVerificationRequest = z.object({
    email: z.email()
});

/**
 * ResendVerificationResponse
 */
export const zResendVerificationResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('If that email address is in our system and unverified, a new confirmation link has been sent.')
});

/**
 * ResetPasswordRequest
 */
export const zResetPasswordRequest = z.object({
    new_password: z.string().min(8)
});

/**
 * ResetPasswordResponse
 */
export const zResetPasswordResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password has been reset successfully.')
});

/**
 * RetryJobResponse
 */
export const zRetryJobResponse = z.object({
    success: z.boolean().optional().default(true),
    original_job_id: z.string(),
    new_job_id: z.string(),
    function: z.string()
});

/**
 * RoleAction
 */
export const zRoleAction = z.enum([
    'create',
    'read',
    'update',
    'delete'
]);

/**
 * CreateGrantsRequest
 */
export const zCreateGrantsRequest = z.object({
    user_id: z.uuid(),
    role_id: z.uuid(),
    feature_id: z.uuid(),
    actions: z.array(zRoleAction).min(1),
    effect: zGrantEffect.optional().default('allow'),
    starts_at: z.iso.datetime().nullish(),
    expires_at: z.iso.datetime().nullish(),
    reason: z.string().max(500).nullish()
});

/**
 * RolePermissionRecordResponse
 */
export const zRolePermissionRecordResponse = z.object({
    feature_id: z.uuid(),
    feature_slug: z.string(),
    feature_name: z.string(),
    action: zRoleAction,
    effect: zGrantEffect
});

/**
 * RolePermissionRequest
 */
export const zRolePermissionRequest = z.object({
    feature_id: z.uuid(),
    actions: z.array(zRoleAction).min(1),
    effect: zGrantEffect.optional().default('allow')
});

/**
 * RoleCreateRequest
 */
export const zRoleCreateRequest = z.object({
    name: z.string().min(1).max(100),
    description: z.string().max(1000).nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRequest).optional()
});

/**
 * RolePermissionResponse
 */
export const zRolePermissionResponse = z.object({
    feature_slug: z.string(),
    feature_name: z.string(),
    action: zRoleAction,
    effect: zGrantEffect
});

/**
 * AssignableRoleResponse
 */
export const zAssignableRoleResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionResponse).optional()
});

/**
 * AssignableRoleListResponse
 */
export const zAssignableRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAssignableRoleResponse)
});

/**
 * ChangeUserRoleResponse
 */
export const zChangeUserRoleResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    role_id: z.uuid(),
    role_name: z.string(),
    permissions: z.array(zRolePermissionResponse).optional(),
    message: z.string().optional().default('User role updated successfully.')
});

/**
 * RoleRecordResponse
 */
export const zRoleRecordResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRecordResponse).optional()
});

/**
 * RoleListResponse
 */
export const zRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zRoleRecordResponse)
});

/**
 * RoleResponse
 */
export const zRoleResponse = z.object({
    success: z.boolean().optional().default(true),
    data: zRoleRecordResponse,
    message: z.string().optional().default('Role saved successfully.')
});

/**
 * RoleUpdateRequest
 */
export const zRoleUpdateRequest = z.object({
    name: z.string().min(1).max(100),
    description: z.string().max(1000).nullish(),
    is_default: z.boolean().optional().default(false),
    is_system: z.boolean().optional().default(false),
    permissions: z.array(zRolePermissionRequest).optional()
});

/**
 * SendUserPasswordResetResponse
 */
export const zSendUserPasswordResetResponse = z.object({
    success: z.boolean().optional().default(true),
    message: z.string().optional().default('Password reset link sent successfully.')
});

/**
 * UpdateAssignmentRequest
 */
export const zUpdateAssignmentRequest = z.object({
    expires_at: z.iso.datetime().nullable()
});

/**
 * UpdateVenueRequest
 */
export const zUpdateVenueRequest = z.object({
    name: z.string().nullish(),
    description: z.string().nullish(),
    address_line: z.string().nullish(),
    city: z.string().nullish(),
    province: z.string().nullish(),
    postal_code: z.string().nullish(),
    country: z.string().nullish(),
    region: z.string().nullish(),
    capacity: z.int().nullish(),
    venue_type: z.string().nullish(),
    contact_name: z.string().nullish(),
    contact_phone: z.string().nullish(),
    contact_email: z.string().nullish()
});

/**
 * UpdateVenueResponse
 */
export const zUpdateVenueResponse = z.object({
    success: z.boolean().optional().default(true),
    venue_id: z.uuid(),
    name: z.string().nullish(),
    message: z.string().optional().default('Venue updated successfully.')
});

/**
 * UserGrantResponse
 */
export const zUserGrantResponse = z.object({
    id: z.uuid(),
    user_id: z.uuid(),
    feature_id: z.uuid(),
    role_id: z.uuid(),
    action: zRoleAction,
    effect: zGrantEffect,
    reason: z.string().nullable(),
    starts_at: z.iso.datetime().nullish(),
    expires_at: z.iso.datetime().nullish(),
    granted_by: z.uuid().nullable()
});

/**
 * CreateGrantsResponse
 */
export const zCreateGrantsResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserGrantResponse),
    message: z.string().optional().default('Grants created successfully.')
});

/**
 * UserGrantListResponse
 */
export const zUserGrantListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserGrantResponse),
    total: z.int()
});

/**
 * UserOnboardingRequest
 */
export const zUserOnboardingRequest = z.object({
    alias: z.string().min(3).max(100),
    first_name: z.string().min(1).max(100),
    last_name: z.string().min(1).max(100),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().max(150).nullish(),
    bio: z.string().max(500).nullish()
});

/**
 * UserOnboardingResponse
 */
export const zUserOnboardingResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    alias: z.string(),
    first_name: z.string(),
    last_name: z.string(),
    age_group: zAgeGroup,
    gender: zGender,
    education_level: zEducationLevel,
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    message: z.string().optional().default('Onboarding completed successfully.'),
    access_token: z.string()
});

/**
 * UserPermissionsResponse
 */
export const zUserPermissionsResponse = z.object({
    success: z.boolean().optional().default(true),
    permissions: z.record(z.string(), z.boolean())
});

/**
 * UserRoleAssignmentResponse
 */
export const zUserRoleAssignmentResponse = z.object({
    success: z.boolean().optional().default(true),
    id: z.uuid(),
    user_id: z.uuid(),
    role_id: z.uuid(),
    expires_at: z.iso.datetime().nullish(),
    assigned_by: z.uuid().nullable(),
    assigned_at: z.iso.datetime()
});

/**
 * UserRoleListResponse
 */
export const zUserRoleListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zUserRoleAssignmentResponse),
    total: z.int()
});

/**
 * UserStatus
 */
export const zUserStatus = z.enum([
    'active',
    'inactive',
    'locked',
    'deleted'
]);

/**
 * AdminUserAccountDetailResponse
 */
export const zAdminUserAccountDetailResponse = z.object({
    success: z.boolean().optional().default(true),
    user_id: z.uuid(),
    name: z.string(),
    email: z.string(),
    status: zUserStatus,
    role_id: z.uuid().nullish(),
    role_name: z.string().nullish(),
    alias: z.string().nullish(),
    first_name: z.string().nullish(),
    last_name: z.string().nullish(),
    age_group: zAgeGroup.nullish(),
    gender: zGender.nullish(),
    education_level: zEducationLevel.nullish(),
    occupation: z.string().nullish(),
    bio: z.string().nullish(),
    onboarding_completed: z.boolean(),
    onboarding_completed_at: z.string().nullish(),
    email_verified: z.boolean(),
    email_verified_at: z.string().nullish(),
    password_change_at: z.string().nullish(),
    failed_login_attempts: z.int(),
    locked_until: z.string().nullish(),
    last_login_at: z.string().nullish(),
    last_activity_at: z.string().nullish(),
    login_count: z.int(),
    deletion_requested_at: z.string().nullish(),
    deletion_scheduled_for: z.string().nullish(),
    deletion_requested_by: z.uuid().nullish(),
    deletion_reason: z.string().nullish(),
    deleted_at: z.string().nullish(),
    created_at: z.string().nullish(),
    updated_at: z.string().nullish(),
    role_permissions: z.array(zRolePermissionResponse).optional()
});

/**
 * AdminUserAccountSummaryResponse
 */
export const zAdminUserAccountSummaryResponse = z.object({
    user_id: z.uuid(),
    name: z.string(),
    alias: z.string().nullish(),
    email: z.string(),
    role_id: z.uuid().nullish(),
    role_name: z.string().nullish(),
    status: zUserStatus,
    deletion_scheduled_for: z.string().nullish()
});

/**
 * AdminUserAccountListResponse
 */
export const zAdminUserAccountListResponse = z.object({
    success: z.boolean().optional().default(true),
    data: z.array(zAdminUserAccountSummaryResponse),
    pagination: zAdminUserAccountPaginationResponse
});

/**
 * ValidationError
 */
export const zValidationError = z.object({
    loc: z.array(z.union([z.string(), z.int()])),
    msg: z.string(),
    type: z.string(),
    input: z.unknown().optional(),
    ctx: z.record(z.string(), z.unknown()).optional()
});

/**
 * HTTPValidationError
 */
export const zHttpValidationError = z.object({
    detail: z.array(zValidationError).optional()
});

/**
 * ValidationErrorResponse
 */
export const zValidationErrorResponse = z.object({
    success: z.boolean().optional().default(false),
    detail: z.array(z.unknown())
});

/**
 * VenueResponse
 */
export const zVenueResponse = z.object({
    id: z.uuid(),
    name: z.string(),
    description: z.string().nullable(),
    address_line: z.string(),
    city: z.string(),
    province: z.string(),
    postal_code: z.string(),
    region: z.string(),
    country: z.string(),
    capacity: z.int(),
    venue_type: z.string(),
    contact_name: z.string(),
    contact_phone: z.string(),
    contact_email: z.string(),
    created_at: z.iso.datetime().nullable()
});

/**
 * VerifyEmailResponse
 */
export const zVerifyEmailResponse = z.object({
    success: z.boolean().optional().default(true),
    access_token: z.string(),
    refresh_token: z.string(),
    token_type: z.string().optional().default('bearer'),
    message: z.string().optional().default('Email verified successfully.')
});

/**
 * WorkerHealthEntrySchema
 */
export const zWorkerHealthEntrySchema = z.object({
    raw: z.string(),
    timestamp: z.string().nullable(),
    j_complete: z.int(),
    j_failed: z.int(),
    j_retried: z.int(),
    j_ongoing: z.int(),
    queued: z.int()
});

/**
 * QueueStatsResponse
 */
export const zQueueStatsResponse = z.object({
    success: z.boolean().optional().default(true),
    queue_name: z.string(),
    pending: z.int(),
    in_progress: z.int(),
    total_failed: z.int(),
    total_completed: z.int(),
    worker_health: z.array(zWorkerHealthEntrySchema)
});

export const zRegisterUserAuthRegisterPostBody = zRegisterRequest;

/**
 * Successful Response
 */
export const zRegisterUserAuthRegisterPostResponse = zRegisterResponse;

export const zVerifyEmailAuthVerifyTokenGetPath = z.object({
    token: z.string().min(1)
});

/**
 * Successful Response
 */
export const zVerifyEmailAuthVerifyTokenGetResponse = zVerifyEmailResponse;

export const zResendVerificationAuthResendVerificationPostBody = zResendVerificationRequest;

/**
 * Successful Response
 */
export const zResendVerificationAuthResendVerificationPostResponse = zResendVerificationResponse;

export const zLoginAuthLoginPostBody = zLoginRequest;

/**
 * Successful Response
 */
export const zLoginAuthLoginPostResponse = zLoginInitResponse;

export const zLoginVerifyAuthLoginVerifyPostBody = zLoginVerifyRequest;

/**
 * Successful Response
 */
export const zLoginVerifyAuthLoginVerifyPostResponse = zLoginVerifyResponse;

export const zResendOtpAuthLoginResendOtpPostBody = zResendOtpRequest;

/**
 * Successful Response
 */
export const zResendOtpAuthLoginResendOtpPostResponse = zResendOtpResponse;

export const zLogoutAuthLogoutPostBody = zLogoutRequest;

/**
 * Successful Response
 */
export const zLogoutAuthLogoutPostResponse = zLogoutResponse;

export const zRefreshTokenAuthRefreshPostBody = zRefreshTokenRequest;

/**
 * Successful Response
 */
export const zRefreshTokenAuthRefreshPostResponse = zRefreshTokenResponse;

export const zForgotPasswordAuthForgotPasswordPostBody = zForgotPasswordRequest;

/**
 * Successful Response
 */
export const zForgotPasswordAuthForgotPasswordPostResponse = zForgotPasswordResponse;

export const zResetPasswordAuthResetPasswordTokenPostBody = zResetPasswordRequest;

export const zResetPasswordAuthResetPasswordTokenPostPath = z.object({
    token: z.string().min(1)
});

/**
 * Successful Response
 */
export const zResetPasswordAuthResetPasswordTokenPostResponse = zResetPasswordResponse;

export const zGetLoginHistoryUserLoginHistoryGetQuery = z.object({
    limit: z.int().gte(1).lte(50).optional().default(10)
});

/**
 * Successful Response
 */
export const zGetLoginHistoryUserLoginHistoryGetResponse = zLoginHistoryListResponse;

/**
 * Successful Response
 */
export const zGetMyPermissionsUserMePermissionsGetResponse = zUserPermissionsResponse;

export const zCheckAliasUserCheckAliasGetQuery = z.object({
    alias: z.string().min(3).max(100)
});

/**
 * Successful Response
 */
export const zCheckAliasUserCheckAliasGetResponse = zCheckAliasResponse;

export const zUserOnboardingUserOnboardPostBody = zUserOnboardingRequest;

/**
 * Successful Response
 */
export const zUserOnboardingUserOnboardPostResponse = zUserOnboardingResponse;

export const zChangePasswordUserChangePasswordPostBody = zChangePasswordRequest;

/**
 * Successful Response
 */
export const zChangePasswordUserChangePasswordPostResponse = zChangePasswordResponse;

export const zScheduleOwnAccountDeletionUserAccountDeletionPostBody = zDeleteAccountRequest;

/**
 * Successful Response
 */
export const zScheduleOwnAccountDeletionUserAccountDeletionPostResponse = zDeleteAccountResponse;

export const zScheduleAdminAccountDeletionUserTargetUserIdAccountDeletionPostBody = zAdminDeleteAccountRequest;

export const zScheduleAdminAccountDeletionUserTargetUserIdAccountDeletionPostPath = z.object({
    target_user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zScheduleAdminAccountDeletionUserTargetUserIdAccountDeletionPostResponse = zDeleteAccountResponse;

/**
 * Successful Response
 */
export const zListRolesUserAccountsRolesGetResponse = zAssignableRoleListResponse;

export const zListUserAccountsUserAccountsGetQuery = z.object({
    page: z.int().gte(1).optional().default(1),
    page_size: z.int().gte(1).lte(100).optional().default(10),
    search: z.string().max(200).nullish(),
    status: zUserStatus.nullish(),
    role: z.string().nullish()
});

/**
 * Successful Response
 */
export const zListUserAccountsUserAccountsGetResponse = zAdminUserAccountListResponse;

export const zGetUserAccountDetailUserAccountsUserIdGetPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetUserAccountDetailUserAccountsUserIdGetResponse = zAdminUserAccountDetailResponse;

export const zChangeUserRoleUserAccountsUserIdRolePatchBody = zChangeUserRoleRequest;

export const zChangeUserRoleUserAccountsUserIdRolePatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChangeUserRoleUserAccountsUserIdRolePatchResponse = zChangeUserRoleResponse;

export const zChangeUserEmailUserAccountsUserIdEmailPatchBody = zChangeUserEmailRequest;

export const zChangeUserEmailUserAccountsUserIdEmailPatchPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zChangeUserEmailUserAccountsUserIdEmailPatchResponse = zChangeUserEmailResponse;

export const zSendUserPasswordResetUserAccountsUserIdPasswordResetPostPath = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zSendUserPasswordResetUserAccountsUserIdPasswordResetPostResponse = zSendUserPasswordResetResponse;

export const zGetAuditLogsAuditLogsGetQuery = z.object({
    limit: z.int().gte(10).lte(100).optional().default(10),
    cursor: z.string().nullish(),
    user_id: z.uuid().nullish(),
    action_type: zActionType.nullish(),
    resource_type: z.string().nullish(),
    start_date: z.iso.datetime().nullish(),
    end_date: z.iso.datetime().nullish()
});

/**
 * Successful Response
 */
export const zGetAuditLogsAuditLogsGetResponse = zGetAuditLogsResponse;

/**
 * Successful Response
 */
export const zListFeaturesFeaturesGetResponse = zFeatureListResponse;

export const zCreateFeatureFeaturesPostBody = zFeatureCreateRequest;

/**
 * Successful Response
 */
export const zCreateFeatureFeaturesPostResponse = zFeatureResponse;

export const zDeleteFeatureFeaturesFeatureIdDeletePath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteFeatureFeaturesFeatureIdDeleteResponse = z.void();

export const zGetFeatureFeaturesFeatureIdGetPath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetFeatureFeaturesFeatureIdGetResponse = zFeatureResponse;

export const zUpdateFeatureFeaturesFeatureIdPatchBody = zFeatureUpdateRequest;

export const zUpdateFeatureFeaturesFeatureIdPatchPath = z.object({
    feature_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateFeatureFeaturesFeatureIdPatchResponse = zFeatureResponse;

/**
 * Successful Response
 */
export const zListRolesRolesGetResponse = zRoleListResponse;

export const zCreateRoleRolesPostBody = zRoleCreateRequest;

/**
 * Successful Response
 */
export const zCreateRoleRolesPostResponse = zRoleResponse;

export const zDeleteRoleRolesRoleIdDeletePath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteRoleRolesRoleIdDeleteResponse = z.void();

export const zGetRoleRolesRoleIdGetPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetRoleRolesRoleIdGetResponse = zRoleResponse;

export const zUpdateRoleRolesRoleIdPatchBody = zRoleUpdateRequest;

export const zUpdateRoleRolesRoleIdPatchPath = z.object({
    role_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateRoleRolesRoleIdPatchResponse = zRoleResponse;

export const zListUserRolesUserRolesGetQuery = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListUserRolesUserRolesGetResponse = zUserRoleListResponse;

export const zAssignRoleUserRolesPostBody = zAssignRoleRequest;

/**
 * Successful Response
 */
export const zAssignRoleUserRolesPostResponse = zUserRoleAssignmentResponse;

export const zRevokeAssignmentUserRolesAssignmentIdDeletePath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeAssignmentUserRolesAssignmentIdDeleteResponse = z.void();

export const zGetAssignmentUserRolesAssignmentIdGetPath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetAssignmentUserRolesAssignmentIdGetResponse = zUserRoleAssignmentResponse;

export const zUpdateAssignmentUserRolesAssignmentIdPatchBody = zUpdateAssignmentRequest;

export const zUpdateAssignmentUserRolesAssignmentIdPatchPath = z.object({
    assignment_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateAssignmentUserRolesAssignmentIdPatchResponse = zUserRoleAssignmentResponse;

export const zListUserGrantsUserGrantsGetQuery = z.object({
    user_id: z.uuid()
});

/**
 * Successful Response
 */
export const zListUserGrantsUserGrantsGetResponse = zUserGrantListResponse;

export const zCreateGrantsUserGrantsPostBody = zCreateGrantsRequest;

/**
 * Successful Response
 */
export const zCreateGrantsUserGrantsPostResponse = zCreateGrantsResponse;

/**
 * Successful Response
 */
export const zListGrantFeaturesUserGrantsFeaturesGetResponse = zGrantFeatureListResponse;

export const zRevokeGrantUserGrantsGrantIdDeletePath = z.object({
    grant_id: z.uuid()
});

/**
 * Successful Response
 */
export const zRevokeGrantUserGrantsGrantIdDeleteResponse = z.void();

/**
 * Successful Response
 */
export const zGetQueueStatsQueuesGetResponse = zQueueStatsResponse;

/**
 * Successful Response
 */
export const zPurgeDeadJobsQueuesDlqDeleteResponse = zPurgeDeadJobsResponse;

/**
 * Successful Response
 */
export const zListDeadJobsQueuesDlqGetResponse = zListDeadJobsResponse;

export const zRetryDeadJobQueuesDlqJobIdRetryPostPath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zRetryDeadJobQueuesDlqJobIdRetryPostResponse = zRetryJobResponse;

export const zDeleteDeadJobQueuesDlqJobIdDeletePath = z.object({
    job_id: z.string()
});

/**
 * Successful Response
 */
export const zDeleteDeadJobQueuesDlqJobIdDeleteResponse = zDeleteJobResponse;

export const zCreateVenueVenuesPostBody = zCreateVenueRequest;

/**
 * Successful Response
 */
export const zCreateVenueVenuesPostResponse = zCreateVenueResponse;

export const zDeleteVenueVenuesVenueIdDeletePath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zDeleteVenueVenuesVenueIdDeleteResponse = z.void();

export const zGetVenueVenuesVenueIdGetPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zGetVenueVenuesVenueIdGetResponse = zVenueResponse;

export const zUpdateVenueVenuesVenueIdPatchBody = zUpdateVenueRequest;

export const zUpdateVenueVenuesVenueIdPatchPath = z.object({
    venue_id: z.uuid()
});

/**
 * Successful Response
 */
export const zUpdateVenueVenuesVenueIdPatchResponse = zUpdateVenueResponse;

export const zGetUserVenuesVenuesCreatorCreatorIdGetPath = z.object({
    creator_id: z.uuid()
});

/**
 * Response Get User Venues Venues Creator  Creator Id  Get
 *
 * Successful Response
 */
export const zGetUserVenuesVenuesCreatorCreatorIdGetResponse = z.array(zVenueResponse);
