import type {
  DirectoryEvent,
  EventCategory,
  FeaturedEvent,
} from "@/types/event-directory"

export const ALL_EVENTS: DirectoryEvent[] = [
  {
    id: 1,
    day: "04",
    mo: "MAY",
    year: 2026,
    date: "May 04, 2026",
    time: "6:00 PM – 9:00 PM",
    title: "Liquidity Provision 101",
    desc: "Hands-on workshop for first-time LPs. Walk through adding, rebalancing, and exiting positions.",
    venue: "Matina Town Square",
    cat: "Workshops",
    tags: ["DeFi", "Beginner"],
    seats: 48,
    total: 80,
    status: null,
    orb: "lime",
    angle: "115deg",
  },
  {
    id: 2,
    day: "17",
    mo: "MAY",
    year: 2026,
    date: "May 17, 2026",
    time: "2:00 PM – 5:00 PM",
    title: "Cross-Chain Roundtable",
    desc: "Panel with founders from three L2 ecosystems on bridge safety, shared sequencers, composability.",
    venue: "Abreeza Ayala Mall",
    cat: "Meetups",
    tags: ["L2", "Panel"],
    seats: 22,
    total: 60,
    status: "closing",
    orb: "amber",
    angle: "95deg",
  },
  {
    id: 3,
    day: "01",
    mo: "JUN",
    year: 2026,
    date: "June 01, 2026",
    time: "10:00 AM – 6:00 PM (2-day)",
    title: "DeFi Builder's Weekend",
    desc: "Two-day hackathon for Mindanao developers. Ship a prototype, win grants, meet regional VCs.",
    venue: "MAFBEX Grounds",
    cat: "Hackathons",
    tags: ["Hackathon", "Grants"],
    seats: 0,
    total: 120,
    status: null,
    orb: "lime",
    angle: "135deg",
  },
  {
    id: 4,
    day: "22",
    mo: "APR",
    year: 2026,
    date: "April 22, 2026",
    time: "7:00 PM – 10:00 PM",
    title: "Women in Web3 — Davao Chapter",
    desc: "Monthly mixer spotlighting Mindanao women building and leading in crypto, DeFi and infra.",
    venue: "Seda Abreeza",
    cat: "Meetups",
    tags: ["Community", "Networking"],
    seats: 8,
    total: 50,
    status: "closing",
    orb: "amber",
    angle: "105deg",
  },
  {
    id: 5,
    day: "08",
    mo: "MAY",
    year: 2026,
    date: "May 08, 2026",
    time: "9:00 AM – 1:00 PM",
    title: "Smart Contract Auditing Primer",
    desc: "Intro to audit methodology: common patterns, tools, and how to file a meaningful disclosure.",
    venue: "Ateneo de Davao",
    cat: "Workshops",
    tags: ["Security", "Solidity"],
    seats: 30,
    total: 40,
    status: "new",
    orb: "lime",
    angle: "125deg",
  },
  {
    id: 6,
    day: "29",
    mo: "APR",
    year: 2026,
    date: "April 29, 2026",
    time: "3:00 PM – 6:00 PM",
    title: "Stablecoin Forum: Asia Edition",
    desc: "What's next for PHP-pegged stables, remittance rails, and regulatory clarity across ASEAN.",
    venue: "Park Inn Davao",
    cat: "Meetups",
    tags: ["Stablecoins", "Policy"],
    seats: 34,
    total: 90,
    status: null,
    orb: "amber",
    angle: "100deg",
  },
  {
    id: 7,
    day: "15",
    mo: "JUN",
    year: 2026,
    date: "June 15, 2026",
    time: "10:00 AM – 2:00 PM",
    title: "On-Chain Identity Workshop",
    desc: "Soul-bound tokens, attestations, and ENS — practical patterns for community membership.",
    venue: "SMX Convention Center",
    cat: "Workshops",
    tags: ["Identity", "ENS"],
    seats: 42,
    total: 70,
    status: null,
    orb: "lime",
    angle: "110deg",
  },
  {
    id: 8,
    day: "24",
    mo: "JUN",
    year: 2026,
    date: "June 24, 2026",
    time: "4:00 PM – 8:00 PM",
    title: "Treasury Management for DAOs",
    desc: "Case studies from three active DAOs. Diversification, streaming, and multi-sig hygiene.",
    venue: "Dusit Thani Davao",
    cat: "Meetups",
    tags: ["DAO", "Treasury"],
    seats: 52,
    total: 80,
    status: null,
    orb: "lime",
    angle: "130deg",
  },
  {
    id: 9,
    day: "05",
    mo: "JUL",
    year: 2026,
    date: "July 05, 2026",
    time: "9:00 AM – 6:00 PM",
    title: "Mindanao ZK Summit",
    desc: "A full-day deep dive on zero-knowledge proofs, circuits, and the developer toolchain.",
    venue: "SMX Convention Center",
    cat: "Meetups",
    tags: ["ZK", "Research"],
    seats: 128,
    total: 250,
    status: "new",
    orb: "amber",
    angle: "115deg",
  },
]

export const CATEGORIES: EventCategory[] = [
  { key: "All", label: "All Events" },
  { key: "Workshops", label: "Workshops" },
  { key: "Meetups", label: "Meetups" },
  { key: "Hackathons", label: "Hackathons" },
]

export const FEATURED: FeaturedEvent = {
  tag: "FEATURED",
  title: "Davao DeFi End-of-Year Gala 2026",
  desc: "A black-tie celebration closing a landmark year for the Davao DeFi community — keynote, awards, live panel, and an after-hours builder's mixer.",
  date: "December 12, 2026",
  time: "6:00 PM – 12:00 AM",
  venue: "Marco Polo Davao, Grand Ballroom",
}
