/**
 * Mock venues data for Venue Hub
 */

import { Venue, VenueType } from "@/types/venue"

export const MOCK_VENUES: Venue[] = [
  {
    id: 1,
    name: "SMX Convention Center",
    location: "Lanang, Davao City",
    capacity: 500,
    type: VenueType.Convention,
    rating: 4.9,
    reviews: 42,
    contributor: { username: "@camille.eth", date: "Mar 12, 2026" },
    tags: ["AV Ready", "Parking", "WiFi"],
    amenities: ["wifi", "parking", "mic"],
    orb: "lime",
    angle: "115deg",
  },
  {
    id: 2,
    name: "Abreeza Ayala Mall — Function Room A",
    location: "Lanang, Davao City",
    capacity: 120,
    type: VenueType.Ballroom,
    rating: 4.5,
    reviews: 28,
    contributor: { username: "@admin", date: "Feb 20, 2026" },
    tags: ["Central Location", "AV Ready"],
    amenities: ["wifi", "parking", "coffee"],
    orb: "amber",
    angle: "118deg",
  },
  {
    id: 3,
    name: "Matina Town Square — Theatre",
    location: "Matina, Davao City",
    capacity: 300,
    type: VenueType.Theatre,
    rating: 4.7,
    reviews: 35,
    contributor: { username: "@venue.hub", date: "Jan 15, 2026" },
    tags: ["Stage Ready", "Good Acoustics"],
    amenities: ["wifi", "mic", "coffee"],
    orb: "lime",
    angle: "112deg",
  },
  {
    id: 4,
    name: "Hype Hotel — Rooftop Lounge",
    location: "Bajada, Davao City",
    capacity: 80,
    type: VenueType.Lounge,
    rating: 4.8,
    reviews: 19,
    contributor: { username: "@events.davao", date: "Mar 5, 2026" },
    tags: ["Premium", "City Views"],
    amenities: ["coffee", "mic"],
    orb: "amber",
    angle: "116deg",
  },
  {
    id: 5,
    name: "MAFBEX Grounds — Exhibition Hall",
    location: "Buhangin, Davao City",
    capacity: 1000,
    type: VenueType.Convention,
    rating: 4.6,
    reviews: 51,
    contributor: { username: "@davao.venues", date: "Mar 1, 2026" },
    tags: ["Large Capacity", "Outdoor Space"],
    amenities: ["parking", "wifi"],
    orb: "lime",
    angle: "114deg",
  },
  {
    id: 6,
    name: "The Workshop — Coworking Hub",
    location: "Poblacion, Davao City",
    capacity: 150,
    type: VenueType.Coworking,
    rating: 4.4,
    reviews: 22,
    contributor: { username: "@tech.davao", date: "Feb 28, 2026" },
    tags: ["WiFi Included", "Coffee"],
    amenities: ["wifi", "coffee", "mic"],
    orb: "amber",
    angle: "120deg",
  },
  {
    id: 7,
    name: "Crooked Cue Billiards & Bar",
    location: "Banilad, Davao City",
    capacity: 200,
    type: VenueType.Lounge,
    rating: 4.3,
    reviews: 16,
    contributor: { username: "@community.davao", date: "Mar 8, 2026" },
    tags: ["Entertainment", "Social Space"],
    amenities: ["wifi", "coffee"],
    orb: "lime",
    angle: "117deg",
  },
  {
    id: 8,
    name: "UP Mindanao — Performing Arts Theater",
    location: "Mintal, Davao City",
    capacity: 400,
    type: VenueType.Auditorium,
    rating: 4.7,
    reviews: 38,
    contributor: { username: "@cultural.hub", date: "Feb 15, 2026" },
    tags: ["Professional Stage", "Green Room"],
    amenities: ["wifi", "parking", "mic"],
    orb: "amber",
    angle: "119deg",
  },
  {
    id: 9,
    name: "Shrine of the Holy Infant Jesus — Function Hall",
    location: "Poblacion, Davao City",
    capacity: 250,
    type: VenueType.Ballroom,
    rating: 4.6,
    reviews: 24,
    contributor: { username: "@events.coordinator", date: "Jan 28, 2026" },
    tags: ["Elegant", "AV Equipment"],
    amenities: ["parking", "mic", "coffee"],
    orb: "lime",
    angle: "113deg",
  },
  {
    id: 10,
    name: "Azuela Cove — Beach Club",
    location: "Samal Island, Davao",
    capacity: 350,
    type: VenueType.Lounge,
    rating: 4.8,
    reviews: 46,
    contributor: { username: "@beach.events", date: "Mar 3, 2026" },
    tags: ["Beachfront", "Resort Amenities"],
    amenities: ["wifi", "parking", "coffee"],
    orb: "amber",
    angle: "115deg",
  },
  {
    id: 11,
    name: "Davao Convention Center — Grand Ballroom",
    location: "Lanang, Davao City",
    capacity: 800,
    type: VenueType.Ballroom,
    rating: 4.9,
    reviews: 67,
    contributor: { username: "@official.venues", date: "Mar 10, 2026" },
    tags: ["Premium Venue", "Full Service"],
    amenities: ["wifi", "parking", "mic"],
    orb: "lime",
    angle: "116deg",
  },
  {
    id: 12,
    name: "Creative Space Studio — Multipurpose",
    location: "Bajada, Davao City",
    capacity: 180,
    type: VenueType.Studio,
    rating: 4.5,
    reviews: 18,
    contributor: { username: "@creative.community", date: "Feb 18, 2026" },
    tags: ["Flexible Layout", "Modern Equipment"],
    amenities: ["wifi", "coffee", "mic"],
    orb: "amber",
    angle: "121deg",
  },
]
