"""add venue_ratings table and fix relationship issues

Revision ID: 14f1975a2499
Revises: 47b927a40ba1
Create Date: 2026-04-12 15:42:17.544164

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "14f1975a2499"
down_revision: str | Sequence[str] | None = "47b927a40ba1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("venue_ratings", sa.Column("comment", sa.Text(), nullable=True))
    op.alter_column("venue_ratings", "created_at", existing_type=postgresql.TIMESTAMP(), type_=sa.DateTime(timezone=True), existing_nullable=False)
    op.alter_column("venue_ratings", "updated_at", existing_type=postgresql.TIMESTAMP(), type_=sa.DateTime(timezone=True), existing_nullable=False)
    op.drop_constraint(op.f("venue_ratings_user_id_fkey"), "venue_ratings", type_="foreignkey")
    op.create_foreign_key(None, "venue_ratings", "user_profiles", ["user_id"], ["user_id"], ondelete="CASCADE")
    op.alter_column(
        "venues",
        "created_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "venues",
        "updated_at",
        existing_type=postgresql.TIMESTAMP(),
        type_=sa.DateTime(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("idx_venues_created_at"), table_name="venues")
    op.drop_index(op.f("idx_venues_updated_at"), table_name="venues")
    op.create_index("idx_venues_name_city", "venues", ["name", "city"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_venues_name_city", table_name="venues")
    op.create_index(op.f("idx_venues_updated_at"), "venues", ["updated_at"], unique=False)
    op.create_index(op.f("idx_venues_created_at"), "venues", ["created_at"], unique=False)
    op.alter_column(
        "venues",
        "updated_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.alter_column(
        "venues",
        "created_at",
        existing_type=sa.DateTime(timezone=True),
        type_=postgresql.TIMESTAMP(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_constraint(None, "venue_ratings", type_="foreignkey")
    op.create_foreign_key(op.f("venue_ratings_user_id_fkey"), "venue_ratings", "users", ["user_id"], ["id"], ondelete="CASCADE")
    op.alter_column("venue_ratings", "updated_at", existing_type=sa.DateTime(timezone=True), type_=postgresql.TIMESTAMP(), existing_nullable=False)
    op.alter_column("venue_ratings", "created_at", existing_type=sa.DateTime(timezone=True), type_=postgresql.TIMESTAMP(), existing_nullable=False)
    op.drop_column("venue_ratings", "comment")
    # ### end Alembic commands ###
