"""add volunteers table

Revision ID: 1890e97addc8
Revises: 14f1975a2499
Create Date: 2026-04-12 18:14:05.867413

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1890e97addc8"
down_revision: str | Sequence[str] | None = "14f1975a2499"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "volunteers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("contact_phone", sa.String(length=20), nullable=False),
        sa.Column("role", sa.Enum("ORGANIZER", "COORDINATOR", "VOLUNTEER", name="volunteerrole", native_enum=False), nullable=False),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", "SUSPENDED", name="volunteerstatus", native_enum=False), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_volunteers_email", "volunteers", ["email"], unique=False)
    op.create_index("idx_volunteers_role", "volunteers", ["role"], unique=False)
    op.create_index("idx_volunteers_status", "volunteers", ["status"], unique=False)
    op.create_index("idx_volunteers_user_id", "volunteers", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_volunteers_user_id", table_name="volunteers")
    op.drop_index("idx_volunteers_status", table_name="volunteers")
    op.drop_index("idx_volunteers_role", table_name="volunteers")
    op.drop_index("idx_volunteers_email", table_name="volunteers")
    op.drop_table("volunteers")
    # ### end Alembic commands ###
