"""add image file id in venue

Revision ID: 1a04be8e2874
Revises: ccec128a3da0
Create Date: 2026-04-22 02:46:04.974769

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a04be8e2874'
down_revision: Union[str, Sequence[str], None] = 'ccec128a3da0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_reports',
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('feedback_type', sa.Enum('BUG_REPORT', 'FEATURE_REQUEST', 'COMPLAINT', 'SUGGESTION', 'OTHER', name='feedbacktype', native_enum=False), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('entity_type', sa.Enum('EVENT', 'VENUE', 'USER', 'VOLUNTEER', 'OTHER', name='entitytype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'IN_REVIEW', 'IN_PROGRESS', 'RESOLVED', 'CLOSED', 'REJECTED', name='feedbackstatus', native_enum=False), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severitylevel', native_enum=False), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_feedback_reports_created_by', 'feedback_reports', ['created_by'], unique=False)
    op.create_index('idx_feedback_reports_entity', 'feedback_reports', ['entity_type', 'entity_id'], unique=False)
    op.create_index('idx_feedback_reports_feedback_type', 'feedback_reports', ['feedback_type'], unique=False)
    op.create_index('idx_feedback_reports_severity', 'feedback_reports', ['severity'], unique=False)
    op.create_index('idx_feedback_reports_status', 'feedback_reports', ['status'], unique=False)
    op.add_column('venues', sa.Column('image_file_id', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'image_file_id')
    op.drop_index('idx_feedback_reports_status', table_name='feedback_reports')
    op.drop_index('idx_feedback_reports_severity', table_name='feedback_reports')
    op.drop_index('idx_feedback_reports_feedback_type', table_name='feedback_reports')
    op.drop_index('idx_feedback_reports_entity', table_name='feedback_reports')
    op.drop_index('idx_feedback_reports_created_by', table_name='feedback_reports')
    op.drop_table('feedback_reports')
    # ### end Alembic commands ###
