"""add relationship on venue,rating, and volunteer tables

Revision ID: 28c51337e1e3
Revises: a846595d0052
Create Date: 2026-04-13 00:41:22.903808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '28c51337e1e3'
down_revision: Union[str, Sequence[str], None] = 'a846595d0052'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
