"""add event_sessions table

Revision ID: 2c151236de48
Revises: 503397cf723c
Create Date: 2026-04-21 10:43:03.846444

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c151236de48'
down_revision: Union[str, Sequence[str], None] = '503397cf723c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_sessions',
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('venue_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'CANCELLED', 'COMPLETED', name='eventsessionstatus', native_enum=False), nullable=False),
    sa.Column('session_metadata', sa.JSON(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_sessions_end_datetime', 'event_sessions', ['end_datetime'], unique=False)
    op.create_index('idx_event_sessions_event_id', 'event_sessions', ['event_id'], unique=False)
    op.create_index('idx_event_sessions_start_datetime', 'event_sessions', ['start_datetime'], unique=False)
    op.create_index('idx_event_sessions_status', 'event_sessions', ['status'], unique=False)
    op.create_index('idx_event_sessions_venue_id', 'event_sessions', ['venue_id'], unique=False)
    op.add_column('venues', sa.Column('region', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'region')
    op.drop_index('idx_event_sessions_venue_id', table_name='event_sessions')
    op.drop_index('idx_event_sessions_status', table_name='event_sessions')
    op.drop_index('idx_event_sessions_start_datetime', table_name='event_sessions')
    op.drop_index('idx_event_sessions_event_id', table_name='event_sessions')
    op.drop_index('idx_event_sessions_end_datetime', table_name='event_sessions')
    op.drop_table('event_sessions')
    # ### end Alembic commands ###
