"""add event table

Revision ID: 37c679742eec
Revises: 2e51ed718704
Create Date: 2026-04-13 18:46:01.541466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '37c679742eec'
down_revision: Union[str, Sequence[str], None] = '2e51ed718704'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'PUBLISHED', 'CANCELLED', 'COMPLETED', 'POSTPONED', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_events_created_by', 'events', ['created_by'], unique=False)
    op.create_index('idx_events_end_date', 'events', ['end_date'], unique=False)
    op.create_index('idx_events_start_date', 'events', ['start_date'], unique=False)
    op.create_index('idx_events_status', 'events', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_events_status', table_name='events')
    op.drop_index('idx_events_start_date', table_name='events')
    op.drop_index('idx_events_end_date', table_name='events')
    op.drop_index('idx_events_created_by', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
