"""add volunteer roles table, remove volunteer email

Revision ID: 3a13546f5aac
Revises: 611315ae76ab
Create Date: 2026-05-06 03:34:15.463876

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a13546f5aac'
down_revision: Union[str, Sequence[str], None] = '611315ae76ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('volunteer_custom_roles',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('idx_volunteer_custom_roles_created_by', 'volunteer_custom_roles', ['created_by'], unique=False)
    op.create_index('idx_volunteer_custom_roles_name', 'volunteer_custom_roles', ['name'], unique=False)
    op.add_column('event_sessions', sa.Column('max_slots', sa.Integer(), nullable=True))
    op.add_column('volunteers', sa.Column('volunteer_role_id', sa.UUID(), nullable=False))
    op.drop_index(op.f('idx_volunteers_email'), table_name='volunteers')
    op.drop_index(op.f('idx_volunteers_role'), table_name='volunteers')
    op.drop_constraint(op.f('volunteers_email_key'), 'volunteers', type_='unique')
    op.create_index('idx_volunteers_volunteer_role_id', 'volunteers', ['volunteer_role_id'], unique=False)
    op.create_unique_constraint('uq_volunteers_user_id', 'volunteers', ['user_id'])
    op.create_foreign_key(None, 'volunteers', 'volunteer_custom_roles', ['volunteer_role_id'], ['id'])
    op.drop_column('volunteers', 'role')
    op.drop_column('volunteers', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('volunteers', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.add_column('volunteers', sa.Column('role', sa.VARCHAR(length=11), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'volunteers', type_='foreignkey')
    op.drop_constraint('uq_volunteers_user_id', 'volunteers', type_='unique')
    op.drop_index('idx_volunteers_volunteer_role_id', table_name='volunteers')
    op.create_unique_constraint(op.f('volunteers_email_key'), 'volunteers', ['email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_volunteers_role'), 'volunteers', ['role'], unique=False)
    op.create_index(op.f('idx_volunteers_email'), 'volunteers', ['email'], unique=False)
    op.drop_column('volunteers', 'volunteer_role_id')
    op.drop_column('event_sessions', 'max_slots')
    op.drop_index('idx_volunteer_custom_roles_name', table_name='volunteer_custom_roles')
    op.drop_index('idx_volunteer_custom_roles_created_by', table_name='volunteer_custom_roles')
    op.drop_table('volunteer_custom_roles')
    # ### end Alembic commands ###
