"""migrate 3/30/2026

Revision ID: 81fb4eead42b
Revises: 61a4eac8bb61
Create Date: 2026-03-30 09:13:12.352533

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "81fb4eead42b"
down_revision: str | Sequence[str] | None = "61a4eac8bb61"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column(
            "age_group",
            sa.Enum("CHILD", "TEEN", "ADULT", "SENIOR", name="age_group"),
            nullable=False,
        ),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.Column("occupation", sa.String(length=150), nullable=True),
        sa.Column(
            "education_level",
            sa.Enum(
                "NO_FORMAL_EDUCATION",
                "ELEMENTARY_LEVEL",
                "ELEMENTARY_GRADUATE",
                "JUNIOR_HIGH_SCHOOL_LEVEL",
                "JUNIOR_HIGH_SCHOOL_GRADUATE",
                "SENIOR_HIGH_SCHOOL_LEVEL",
                "SENIOR_HIGH_SCHOOL_GRADUATE",
                "VOCATIONAL_TRADE_CERTIFICATE",
                "COLLEGE_LEVEL_UNDERGRADUATE",
                "ASSOCIATE_DEGREE",
                "BACHELORS_DEGREE",
                "MASTERS_DEGREE",
                "DOCTORATE_DEGREE",
                name="education_level",
            ),
            nullable=False,
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        sa.UniqueConstraint("user_id"),
    )
    op.drop_table("user_roles")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("role", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("user_roles_user_id_fkey"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_roles_pkey")),
        sa.UniqueConstraint(
            "role",
            name=op.f("user_roles_role_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        sa.UniqueConstraint(
            "user_id",
            name=op.f("user_roles_user_id_key"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("user_profiles")
    # ### end Alembic commands ###
