"""add event_feedback table and event_participants checkin columns

Revision ID: a8d756cc0338
Revises: 2029f73df75b
Create Date: 2026-05-15 22:42:35.477969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8d756cc0338'
down_revision: Union[str, Sequence[str], None] = '2029f73df75b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_feedback',
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_app_feedback_created_at', 'app_feedback', ['created_at'], unique=False)
    op.create_index('idx_app_feedback_rating', 'app_feedback', ['rating'], unique=False)
    op.create_table('event_feedback',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('event_id', sa.UUID(), nullable=False),
    sa.Column('participant_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('suggestion', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['participant_id'], ['event_participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_event_feedback_event_id', 'event_feedback', ['event_id'], unique=False)
    op.create_index('idx_event_feedback_participant_id', 'event_feedback', ['participant_id'], unique=False)
    op.create_index('idx_event_feedback_rating', 'event_feedback', ['event_id', 'rating'], unique=False)
    op.create_index('idx_event_feedback_user_event', 'event_feedback', ['user_id', 'event_id'], unique=True)
    op.create_index('idx_event_feedback_user_id', 'event_feedback', ['user_id'], unique=False)
    op.add_column('event_participants', sa.Column('is_checked_in', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.add_column('event_participants', sa.Column('checked_in_time', sa.DateTime(timezone=True), nullable=True))
    op.add_column('event_participants', sa.Column('checked_in_by', sa.UUID(), nullable=True))
    op.create_index('idx_event_participants_checked_in_by', 'event_participants', ['checked_in_by'], unique=False)
    op.create_index('idx_event_participants_is_checked_in', 'event_participants', ['is_checked_in'], unique=False)
    op.create_foreign_key(None, 'event_participants', 'users', ['checked_in_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_participants', type_='foreignkey')
    op.drop_index('idx_event_participants_is_checked_in', table_name='event_participants')
    op.drop_index('idx_event_participants_checked_in_by', table_name='event_participants')
    op.drop_column('event_participants', 'checked_in_by')
    op.drop_column('event_participants', 'checked_in_time')
    op.drop_column('event_participants', 'is_checked_in')
    op.drop_index('idx_event_feedback_user_id', table_name='event_feedback')
    op.drop_index('idx_event_feedback_user_event', table_name='event_feedback')
    op.drop_index('idx_event_feedback_rating', table_name='event_feedback')
    op.drop_index('idx_event_feedback_participant_id', table_name='event_feedback')
    op.drop_index('idx_event_feedback_event_id', table_name='event_feedback')
    op.drop_table('event_feedback')
    op.drop_index('idx_app_feedback_rating', table_name='app_feedback')
    op.drop_index('idx_app_feedback_created_at', table_name='app_feedback')
    op.drop_table('app_feedback')
    # ### end Alembic commands ###
