"""fix deleted at index on user model

Revision ID: c40e9f92494e
Revises: cddebee147ac
Create Date: 2026-04-12 00:35:40.320705

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c40e9f92494e"
down_revision: str | Sequence[str] | None = "cddebee147ac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "action_type",
            sa.Enum("CREATE", "READ", "UPDATE", "DELETE", "LOGIN", "LOGOUT", "VERIFY", "EXPORT", "IMPORT", name="action_type"),
            nullable=False,
        ),
        sa.Column("resource_type", sa.String(length=255), nullable=False),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("status", sa.Enum("SUCCESS", "FAILURE", name="audit_log_status"), nullable=False),
        sa.Column("old_values", sa.JSON(), nullable=True),
        sa.Column("new_values", sa.JSON(), nullable=True),
        sa.Column("additional_context", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_audit_logs_action_type", "audit_logs", ["action_type"], unique=False)
    op.create_index("idx_audit_logs_cursor", "audit_logs", ["id", "timestamp"], unique=False)
    op.create_index("idx_audit_logs_resource", "audit_logs", ["resource_type", "resource_id"], unique=False)
    op.create_index("idx_audit_logs_timestamp", "audit_logs", ["timestamp"], unique=False)
    op.create_index("idx_audit_logs_user_id", "audit_logs", ["user_id"], unique=False)
    op.create_table(
        "features",
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("slug"),
    )
    op.create_index("idx_features_is_enabled", "features", ["is_enabled"], unique=False)
    op.create_index("idx_features_slug", "features", ["slug"], unique=False)
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_index("idx_roles_is_default", "roles", ["is_default"], unique=False)
    op.create_index("idx_roles_is_system", "roles", ["is_system"], unique=False)
    op.create_index("idx_roles_name", "roles", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password", sa.Text(), nullable=False),
        sa.Column("onboarding_completed", sa.Boolean(), nullable=False),
        sa.Column("onboarding_completed_at", sa.DateTime(), nullable=True),
        sa.Column("status", sa.Enum("ACTIVE", "INACTIVE", "LOCKED", "DELETED", name="user_status"), nullable=False),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("email"),
    )
    op.create_index("idx_users_not_deleted", "users", ["id"], unique=False, postgresql_where=sa.text("deleted_at IS NULL"))
    op.create_index("idx_users_status", "users", ["status"], unique=False)
    op.create_table(
        "login_history",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("browser", sa.String(length=100), nullable=True),
        sa.Column("os", sa.String(length=100), nullable=True),
        sa.Column("device_type", sa.String(length=50), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("region", sa.String(length=100), nullable=True),
        sa.Column("country", sa.String(length=100), nullable=True),
        sa.Column("successful", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_login_history_successful", "login_history", ["successful"], unique=False)
    op.create_index("idx_login_history_user_id", "login_history", ["user_id"], unique=False)
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("revoked_at", sa.DateTime(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=False),
        sa.Column("last_used_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_refresh_tokens_token_hash"), "refresh_tokens", ["token_hash"], unique=True)
    op.create_table(
        "role_permissions",
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="role_action"), nullable=False),
        sa.Column("effect", sa.Enum("ALLOW", "DENY", name="grant_effect"), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_role_permissions_role_feature_action", "role_permissions", ["role_id", "feature_id", "action"], unique=False)
    op.create_table(
        "user_activity",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("last_login_at", sa.DateTime(), nullable=True),
        sa.Column("last_activity_at", sa.DateTime(), nullable=True),
        sa.Column("login_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_user_activity_last_activity", "user_activity", ["last_activity_at"], unique=False)
    op.create_index("idx_user_activity_last_login", "user_activity", ["last_login_at"], unique=False)
    op.create_table(
        "user_grants",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("feature_id", sa.UUID(), nullable=False),
        sa.Column("action", sa.Enum("CREATE", "READ", "UPDATE", "DELETE", name="role_action"), nullable=False),
        sa.Column("effect", sa.Enum("ALLOW", "DENY", name="grant_effect"), nullable=False),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("granted_by", sa.UUID(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["feature_id"], ["features.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["granted_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_grants_expires_at", "user_grants", ["expires_at"], unique=False)
    op.create_index("idx_user_grants_user_role_feature_action", "user_grants", ["user_id", "role_id", "feature_id", "action"], unique=False)
    op.create_table(
        "user_profiles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("alias", sa.String(length=100), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("image_file_id", sa.String(length=255), nullable=True),
        sa.Column("age_group", sa.Enum("CHILD", "TEEN", "ADULT", "SENIOR", name="age_group"), nullable=False),
        sa.Column("gender", sa.Enum("MALE", "FEMALE", name="gender"), nullable=False),
        sa.Column("occupation", sa.String(length=150), nullable=True),
        sa.Column(
            "education_level",
            sa.Enum(
                "NO_FORMAL_EDUCATION",
                "ELEMENTARY_LEVEL",
                "ELEMENTARY_GRADUATE",
                "JUNIOR_HIGH_SCHOOL_LEVEL",
                "JUNIOR_HIGH_SCHOOL_GRADUATE",
                "SENIOR_HIGH_SCHOOL_LEVEL",
                "SENIOR_HIGH_SCHOOL_GRADUATE",
                "VOCATIONAL_TRADE_CERTIFICATE",
                "COLLEGE_LEVEL_UNDERGRADUATE",
                "ASSOCIATE_DEGREE",
                "BACHELORS_DEGREE",
                "MASTERS_DEGREE",
                "DOCTORATE_DEGREE",
                name="education_level",
            ),
            nullable=False,
        ),
        sa.Column("bio", sa.Text(), nullable=True),
        sa.Column("preferences", sa.JSON(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("alias"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("role_id", sa.UUID(), nullable=False),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column("assigned_by", sa.UUID(), nullable=True),
        sa.Column("assigned_at", sa.DateTime(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["assigned_by"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_user_roles_expires_at", "user_roles", ["expires_at"], unique=False)
    op.create_index("idx_user_roles_user_role", "user_roles", ["user_id", "role_id"], unique=False)
    op.create_table(
        "user_security",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verified_at", sa.DateTime(), nullable=True),
        sa.Column("password_change_at", sa.DateTime(), nullable=True),
        sa.Column("failed_login_attempts", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_index("idx_user_security_email_verified", "user_security", ["email_verified"], unique=False)
    op.create_index("idx_user_security_locked_until", "user_security", ["locked_until"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_user_security_locked_until", table_name="user_security")
    op.drop_index("idx_user_security_email_verified", table_name="user_security")
    op.drop_table("user_security")
    op.drop_index("idx_user_roles_user_role", table_name="user_roles")
    op.drop_index("idx_user_roles_expires_at", table_name="user_roles")
    op.drop_table("user_roles")
    op.drop_table("user_profiles")
    op.drop_index("idx_user_grants_user_role_feature_action", table_name="user_grants")
    op.drop_index("idx_user_grants_expires_at", table_name="user_grants")
    op.drop_table("user_grants")
    op.drop_index("idx_user_activity_last_login", table_name="user_activity")
    op.drop_index("idx_user_activity_last_activity", table_name="user_activity")
    op.drop_table("user_activity")
    op.drop_index("idx_role_permissions_role_feature_action", table_name="role_permissions")
    op.drop_table("role_permissions")
    op.drop_index(op.f("ix_refresh_tokens_token_hash"), table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_index("idx_login_history_user_id", table_name="login_history")
    op.drop_index("idx_login_history_successful", table_name="login_history")
    op.drop_table("login_history")
    op.drop_index("idx_users_status", table_name="users")
    op.drop_index("idx_users_not_deleted", table_name="users", postgresql_where=sa.text("deleted_at IS NULL"))
    op.drop_table("users")
    op.drop_index("idx_roles_name", table_name="roles")
    op.drop_index("idx_roles_is_system", table_name="roles")
    op.drop_index("idx_roles_is_default", table_name="roles")
    op.drop_table("roles")
    op.drop_index("idx_features_slug", table_name="features")
    op.drop_index("idx_features_is_enabled", table_name="features")
    op.drop_table("features")
    op.drop_index("idx_audit_logs_user_id", table_name="audit_logs")
    op.drop_index("idx_audit_logs_timestamp", table_name="audit_logs")
    op.drop_index("idx_audit_logs_resource", table_name="audit_logs")
    op.drop_index("idx_audit_logs_cursor", table_name="audit_logs")
    op.drop_index("idx_audit_logs_action_type", table_name="audit_logs")
    op.drop_table("audit_logs")
    # ### end Alembic commands ###
