import uuid
from typing import Protocol
from app.domain.entities.venue_rating_entities import VenueRating, PublicVenueRating


class IVenueRatingRepository(Protocol):
    async def create(self, rating: VenueRating) -> PublicVenueRating: ...
    async def get_by_id(self, rating_id: uuid.UUID) -> VenueRating | None: ...
    async def get_by_user_and_venue(self, user_id: uuid.UUID, venue_id: uuid.UUID) -> VenueRating | None: ...
    async def get_by_venue(self, venue_id: uuid.UUID) -> list[PublicVenueRating]: ...
    async def update(self, rating: VenueRating) -> PublicVenueRating: ...
    async def delete(self, rating_id: uuid.UUID) -> None: ...