import uuid
from typing import Protocol
from app.domain.entities.venue_entities import Venue, PublicVenue


class IVenueRepository(Protocol):
    async def create(self, venue: Venue) -> PublicVenue: ...
    async def update(self, venue: Venue) -> PublicVenue: ...
    async def delete(self, venue_id: uuid.UUID) -> None: ...
    async def get_by_id(self, venue_id: uuid.UUID) -> Venue | None: ...
    async def get_by_creator(self, creator_id: uuid.UUID) -> list[PublicVenue]: ...
